### ISSUE TITLE
Configure Bollinger Band Time period.

### ISSUE THREAD

**Issue by sirajperson** [mdeverdelhan/ta4j#100]
I'd just like to begin with a huge thank you for this library. I've been testing it for 3 quarters and have enjoyed working with it. 

I'd like to know if there is a way to configure the Bollinger Band middle from what seems to be the default 20 periods. I tried extending the class, and adding the calculate functions from the EMAIndicator class, but that doesn't seem to work as it causes a problem because of the need of the recursive cached indicator class. In short, I was trying to extend the Bollinger middle indicator class to take the following arguments: 

`BollingerBandsMiddleIndicator(Indicator<Decimal> closePriceIndicator, int timePeriod);`

That way I could fine tune the Bollinger band indicator to be more functional with specific security back testing.

**Comment by sirajperson** [comment]
My mistake was that I had been using the EMA in the first place... LoL. Newbie booboo. 

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:bollinger_bands

After extending the class BollingerBandMiddleIndicator, and adapting the SMAIndicator code, the Bollinger band middle indicator was correctly configured.

**Comment by dan-lind** [comment]
Not sure if I missunderstand what you are trying to do, but can't you just do
```
SMAIndicator sma = new SMAIndicator(new ClosePriceIndicator(<data>), 20);
BollingerBandsMiddleIndicator bbmSMA = new BollingerBandsMiddleIndicator(sma);
```

**Comment by mdeverdelhan** [comment]
Thank you @dan-lind! Same comment.

**Comment by ankitsaini12585** [comment]
Hi Guys!
I am a new bee to ta4j. I am not sure whether i am doing it correctly or not.
I am trying to calculate bollinger band values for it over a period of 20 days.
The series contains 1 year of data, now doing as shown below:

 ```
ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
 SMAIndicator sma = new SMAIndicator(closePrice, 20);
 BollingerBandsMiddleIndicator bm = new BollingerBandsMiddleIndicator(sma);
 BollingerBandsUpperIndicator bu = new BollingerBandsUpperIndicator(bm, sma);
 BollingerBandsLowerIndicator bl = new BollingerBandsLowerIndicator(bm, sma);
```

Now when plotting upper, closePrice and lower band on chart, it shows negative values. But in actual bollinger chart in 3rd party tools shows positive values only. 

Please suggest me what to do and how!

**Comment by ankitsaini12585** [comment]
Thankyou so much @team172011 !
I will study the links you shared. After implementing it as in the example link you shared it is showing correct values. 
Thanks once again! Happy TA!

**Comment by team172011** [comment]
You are welcome!
