### ISSUE TITLE
Technical indicator documentation

### ISSUE THREAD

**Issue by orbennatan** [mdeverdelhan/ta4j#101]
I would like to use TA4J for a trading project. 
I tried to find documentation on the internet describing each one of the indicators and the way it is commonly used.
I found for some but could not find for other. 
Is there a list of links in investopedia or other web sites which corresponds to the list of indicators supported by the library appearing here?
https://oss.sonatype.org/service/local/repositories/releases/archive/eu/verdelhan/ta4j/0.8/ta4j-0.8-javadoc.jar/!/eu/verdelhan/ta4j/Indicator.html
Some examples for indicators I failed to learn about due to lack of info are:
Real Body
Open Price (and some other price indicators).
Would be great if the docs or even comments in the library will have a link to investopedia so it will be easier to connect to a well known indicator you can learn about.
This is looks like a great project and I will start using it next week.
Thanks.
Or

**Comment by mdeverdelhan** [comment]
Hi and thank you for your interest.

Unfortunatelly there isn't.

Open price is self-explanatory. Real body already has a link (in the javadoc) to its StockCharts definition.
If it isn't enough for you then:
  * Grab more info where you can
  * Feel free to update the documentation and/or make a PR

Marc
