### ISSUE TITLE
RSIIndicator returns NaN when rsi == 100

### ISSUE THREAD

**Issue by sirajperson** [mdeverdelhan/ta4j#102]
It seems that whenever the RSI indicator should be a value of 100, the calculate() method produces a nan value in the return statement from the relativeStrength method. 

This is can be problematic, as such in my classes I have replaced it with the following, which tests for values where the average high and low equal a nan value:

    /**
     * @param index
     * @return the relative strength
     */
    private Decimal relativeStrength(int index) {
        if (index == 0) {
            return Decimal.ZERO;
        }
        Decimal averageGain = averageGainIndicator.getValue(index);
        Decimal averageLoss = averageLossIndicator.getValue(index);
        Decimal rs = averageGain.dividedBy(averageLoss);
        if (rs.isNaN())
            return Decimal.HUNDRED;
        else
            return rs;
    }

**Comment by sirajperson** [comment]
This may be more concise:
   
    /**
     * @param index
     * @return the relative strength
     */
    private Decimal relativeStrength(int index) {
        if (index == 0) {
            return Decimal.ZERO;
        }
        Decimal averageGain = averageGainIndicator.getValue(index);
        Decimal averageLoss = averageLossIndicator.getValue(index);
        return (averageLoss == Decimal.ZERO) ? 
             Decimal.HUNDRED : averageGain.dividedBy(averageLoss);
    }

**Comment by sirajperson** [comment]
This may be a little more concise:

/**
     * @param index
     * @return the relative strength
     */
    private Decimal relativeStrength(int index) {
        if (index == 0) {
            return Decimal.ZERO;
        }
        Decimal averageGain = averageGainIndicator.getValue(index);
        Decimal averageLoss = averageLossIndicator.getValue(index);
        return averageLoss.equals(Decimal.ZERO) ?
                Decimal.HUNDRED : averageGain.dividedBy(averageLoss);
    }

**Comment by mdeverdelhan** [comment]
I pushed a slightly more elaborated fix than yours. Anyway thank you for pointing this out. :)
