### ISSUE TITLE
Strange calculation with Ichimoku Indicator

### ISSUE THREAD

**Issue by k830206** [mdeverdelhan/ta4j#105]
Hi,

I've imported the library and tested Ichimoku Cloud, but it was mismatched with my own result.
So I tried to see your source for "AbstractIchimokuLineIndicator" class and I found a bug for "calculate" method like: 

return periodHigh.getValue(index).plus(periodLow.getValue(index)**.dividedBy(Decimal.TWO))**;

I think it should be changed like:

return periodHigh.getValue(index).plus(periodLow.getValue(index**)).dividedBy(Decimal.TWO)**;

Regards,

JeongSuk Lee

**Comment by gcauchis** [comment]
My mistake... sorry and thanks

**Comment by mdeverdelhan** [comment]
Thank you both:
@k830206 for pointing this out
@gcauchis for your reactivity
