### ISSUE TITLE
Examples still working?

### ISSUE THREAD

**Issue by GeeZs** [mdeverdelhan/ta4j#108]
Hello, Im just trying to run the examples and everytime I get the same exception:

`Exception in thread "main" java.lang.NullPointerException
    at java.io.Reader.<init>(Reader.java:78)
    at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
    at ta4jexamples.loaders.CsvTradesLoader.loadBitstampSeries(CsvTradesLoader.java:56)
    at ta4jexamples.loaders.CsvTradesLoader.main(CsvTradesLoader.java:136)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)` 

I guess I did smth wrong. 
Here is my .iml info:

`<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/java" isTestSource="false" />
    </content>

```
<orderEntry type="inheritedJdk" />
<orderEntry type="sourceFolder" forTests="false" />
<orderEntry type="module" module-name="main1" exported="" />
<orderEntry type="module" module-name="test" exported="" />
<orderEntry type="library" exported="" name="hamcrest-core-1.3" level="project" />
<orderEntry type="library" exported="" name="joda-time-2.4-javadoc" level="project" />
<orderEntry type="library" exported="" name="slf4j-1.7" level="project" />
<orderEntry type="library" exported="" name="commons-math3-3.0" level="project" />
<orderEntry type="library" exported="" name="opencsv-2.3" level="project" />
<orderEntry type="library" exported="" name="ch.qos.logback.classic-0.9.28" level="project" />
<orderEntry type="library" exported="" name="logback-core-1.0.13" level="project" />
```

  </component>
</module>`

Still "stream" variable is "null"

`public static TimeSeries loadBitstampSeries() {

```
    // Reading all lines of the CSV file
    **InputStream stream = CsvTradesLoader.class.getClassLoader().getResourceAsStream("/home/synderen/IdeaProjects/ta4j-master/ta4j-examples/src/main/resources/bitstamp.csv");**//
    CSVReader csvReader = null;
    List<String[]> lines = null;
    try {
        csvReader = new CSVReader(new InputStreamReader(stream, Charset.forName("UTF-8")), ',');
        lines = csvReader.readAll();
        lines.remove(0); // Removing header line
    } catch (IOException ioe) {
        Logger.getLogger(CsvTradesLoader.class.getName()).log(Level.SEVERE, "Unable to load trades from CSV", ioe);
    } finally {
        if (csvReader != null) {
            try {
                csvReader.close();
            } catch (IOException ioe) {
            }
        }
    }`
```

Thank you for any help.

**Comment by mdeverdelhan** [comment]
Hello,
Just tested. It is still working.
