### ISSUE TITLE
K indicator get value

### ISSUE THREAD

**Issue by LucasSeveryn** [mdeverdelhan/ta4j#110]
Is this how you query last value for K indicator?

```
StochasticOscillatorKIndicator K = new StochasticOscillatorKIndicator(series, days);
return K.getValue(series.getEnd()).toDouble();
```

I'm checking vs. Bloomberg and values are different. (getting a negative number!)

**Comment by mdeverdelhan** [comment]
Yes it is.
Please check the source code of this indicator and try to explain where the differences are coming from. We will consider as either a bug or a normal behavior.
