### ISSUE TITLE
Big data integration with this Library

### ISSUE THREAD

**Issue by dbclkclk** [mdeverdelhan/ta4j#111]
Awesome library! I have a question, does this library scale well with ElasticSearch? I saw in the documentation that to get historical data on price movement, ta4j implements a caching mechanism; just wondering if this caching mechanism could essentially come from ElasticSearch as oppose to memory? 

Thanks.

**Comment by mdeverdelhan** [comment]
For now the caching mechanism is managed through the `CachedIndicator` class. I wanted to implement that feature (i.e. let the user choose which "storage" he wants) but I did not find the time for that.
