### ISSUE TITLE
Question: How to implement a gradually buying strategy?

### ISSUE THREAD

**Issue by RuralHunter** [mdeverdelhan/ta4j#114]
I'm testing a strategy which would buy more if the price drops 10%. I checked the TimeSeries.run() method and it seems I can not open another trade before the current trade is closed nor I can buy more times on one trade.

**Comment by mdeverdelhan** [comment]
It is not possible with ta4j. It would assume that you still own available money after you entered. Nowadays the lib is not designed for that. It reminds me [an old comment](https://github.com/mdeverdelhan/ta4j/issues/5#issuecomment-47429856).

**Comment by RuralHunter** [comment]
I read the source code and have a re-design idea on one point. Currently, the decision of what trading type is actually in TradingRecord and Trade. If the last order is enter, then the next order have to be exit.That is a bit weird. 
How about to make TradingRecord simpler so it doesn't make any decision but only records the trades, and have the Rule to decide the order(type and amount)? Because the Rule is actually where one makes the most of the customization/decisions in trade policy.

**Comment by team172011** [comment]
I like the suggestion from @RuralHunter . The fact that the **final** functions of class TradeRecord allow just one open trade per time caused me problems. I could not find a way to implement some kind of TradeRecord that allows multiple open trades per time (or at least buy more in current trade) without re-writing the whole library

**Comment by nimo23** [comment]
The "buy, then Sell" or "Sell, then buy" itself should also be treated as a "Strategy". Would be nice to encapsulate this meta-strategy out of the TradingRecord. With this, we can build trading rules such as "buy x(1) -> buy x(2) <y-> sell x(1-2)". 

For example, buy one item by Rule x, trade the record (buy-order-1), buy this item again by Rule y (buy-order-2), trade the record, sell x (of buy-order-1 and buy-order-2) by Rule x. trade the record...

It would make much sense to abstract the rigid "Buy one->Sell one" (vice versa) out into a Meta-Strategy. Would be really nice to have this in t4j.

**Comment by martinklepsch** [comment]
I think one way around this limitation could be adding Ticks via `.addTick`, checking `.shouldEnter` / `.shouldLeave` every time and collecting these signals in an array or something.

Maybe the `Strategy` object could be extended by a function that does this kind of thing as well.

**Comment by team172011** [comment]
Just extending the `Strategy `object does not work, because the result should return a `TradingObject` that contains also the "one trade per time" limitation. In my opinion we have to find a new structure of the `TradingObject`

**Comment by team172011** [comment]
Okay.. i just want to underline that it should be an TradingRecord object to make sure that it is compatible with the rest of the library like ProfirCriterion etc..

**Comment by mdeverdelhan** [comment]
@RuralHunter At the first look I like your idea.
However it would a quite big refactoring on strategy/rule (running and recording) and analysis sides (criteria). Also it will complexify the tests. I will consider any PR about this.

**Comment by CCob** [comment]
I too think this would be a great beneficial feature to an already great library.  One work around, albeit a bit more cumbersome to manage is to have a TradingRecord for the number of simultaneous open orders that your strategy allows.  You of course will need to co-ordinate them if you wanted a (buy), (buy), (sell all) type strategy but certainly doable.

**Comment by mdeverdelhan** [comment]
Please continue this thread on the new repo: https://github.com/ta4j/ta4j
