### ISSUE TITLE
Replace Joda Time to Java 8 Date Time

### ISSUE THREAD

**Issue by andyflury** [mdeverdelhan/ta4j#116]
Are there any plans to replace Joda Time with Java 8 Date Time?

**Comment by sirajperson** [comment]
You know, I was thinking about that... but it would be quite a bit of refactoring.

**Comment by andyflury** [comment]
Would be nice as I think mostly everybody is now using Java 8 Date Time. But I understand that this will be quite a bit of work. Thanks anyway and great job you are doing with ta4j. We have used ta-lib in the past but unfortunately it does not allow continuous calculations of technical indicators which your library does

**Comment by dan-lind** [comment]
ta4j currently uses Java 6. See this discussion for context
https://github.com/mdeverdelhan/ta4j/issues/93

**Comment by sirajperson** [comment]
@andyflury Yep, that's why I switched to this library too... though, it has been a bit less stable than ta-lib admittedly. I'd move only if you were confident enough to solve your own problems or make your own improvements with it. While there are contributors other than the original author, progress is at a slower pace than most individuals or teams develop at.  Hopefully that improves as the library matures.

**Comment by mdeverdelhan** [comment]
Thank you @dan-lind. It may evolve.
I did not know that Date/Time API was such improved in Java 8. We could remove the old Joda dependency. Feel free to make a PR if you get enough time. Furthermore I don't know anyone which is still using Java 6 now.

**Comment by mdeverdelhan** [comment]
Note:
Joda-time Period includes years to milliseconds, java.time Period only includes year/month/day (we have to use Duration for other durations/periods). It involves to refactor TimeSeries#split(...) and TimeSeries#subseries(...) method if we want to manage daylight savings, etc.

See also: http://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html

**Comment by TheCookieLab** [comment]
Yeah I implemented Periods and Durations for the slices in my PR. Long story short after a series of unfortunate events my forked repository got corrupted and thus I deleted it. I still have the Java 8 code in my own version of ta4j but extracting just those changes (again) is going to be a tedious process.

**Comment by mdeverdelhan** [comment]
I think that you can manage it following thoses steps:
  - Fork and clone again
  - Make a raw copy of your local version in the new clone
  - Check the diff according to [what I suggested](https://github.com/mdeverdelhan/ta4j/pull/135#issuecomment-308702682)
  - Commit, push and submit a new PR

**Comment by mdeverdelhan** [comment]
Fixed by #158.
