### ISSUE TITLE
Question: Simple strategy

### ISSUE THREAD

**Issue by jzxcv** [mdeverdelhan/ta4j#123]
Hi.
I'm trying to make a very simple strategy on a time series: enter in the first tick, go on the next one and so on until you go through all the ticks of the time series.
I've been going around for a few days and can not find the solution. I do not know which indicator to use or how to define the rules.
I hope someone can lend a hand.
Thank you.

**Comment by mdeverdelhan** [comment]
See [trading strategies](https://github.com/mdeverdelhan/ta4j/wiki/Trading%20strategies).

Entry rule: https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/trading/rules/JustOnceRule.java

Exit rule: https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/trading/rules/BooleanRule.java#L38
