### ISSUE TITLE
Only buy or only sell strategies?

### ISSUE THREAD

**Issue by mushketer888** [mdeverdelhan/ta4j#124]
Hello all.
I cant clearly understand.
It seems that this library supports only 2 options:
 buy and then close(sell)
 or
 sell and then rebuy to cover?

So it is impossible to use this library to both buy or sell by rules?
I thought about it because i found that it uses OrderType.BUY by default...

**Comment by mdeverdelhan** [comment]
I did not understand. Ta4j supports to enter/exit alternatively. Then it is up-to-you to choose your first move (buy or sell).

**Comment by jsilcam** [comment]
Hi,
I don´t understand either.

I'm working with a time series of mini S$P 500 futures.
In my back testing I want to work with these rules:
rule1 = new CrossedUpIndicatorRule(sma9, sma40);	        		
rule2 = new CrossedDownIndicatorRule(sma9, sma40);

If  CrossedUpIndicatorRule(sma9, sma40) happens, I want to buy.
If  CrossedDownIndicatorRule(sma9, sma40) happens, I want to sell.

If the first thing that happens is CrossedUpIndicatorRule(sma9, sma40) , all trades will be BUY, SELL.
If the first thing that happens is CrossedDownIndicatorRule(sma9, sma40) , all trades will be SELL, BUY.

How can I to implement this in a strategy?

I have done several tests, such as:
//TradingRecord tradingRecord = series.run(new Strategy(rule1, rule2));
//TradingRecord tradingRecord = series.run(new Strategy(rule2, rule1));

But the trades are always of the  "BUY, SELL " type.

**Comment by verona-rupes** [comment]
suppose you are selling short first (SELL) and then buying to cover (BUY) then you need to use this 
overloaded method and pass your OrderTypes in 2 separate runs
    public TradingRecord run(Strategy strategy, OrderType orderType) {
        return run(strategy, orderType, Decimal.NaN);
    }

These are 2 different trades , ideally you get 2 unique order Ids from your broker.

**Comment by jsilcam** [comment]
Thank you @verona-rupes.

After a long time and testing, thanks to your idea, I can move forward.

I have done this:
[TBot104_GitHub.txt](https://github.com/mdeverdelhan/ta4j/files/853084/TBot104_GitHub.txt)

It may not be the best way, but it's a way.

Thank you.
