### ISSUE TITLE
Calculate trading record profit

### ISSUE THREAD

**Issue by AlanInHk** [mdeverdelhan/ta4j#126]
In AverageProfitableTradesCriterion, to check the trading record profit is calculated by 
`series.getTick(exitIndex).getClosePrice().dividedBy(series.getTick(entryIndex).getClosePrice())`

why don't use Trade object entry price and exit price to calculate the profit?

Thank very much of your contribution on the project, it saves many time on my stock analysis.

**Comment by TheCookieLab** [comment]
It's just another way of expressing the profit. Instead of the absolute profit or loss, it's expressed as a percentage instead. If you prefer the absolute number, you can easily write your own class extending AbstractAnalysisCriterion and do the subtraction instead of division.
