### ISSUE TITLE
What about a .toString() method for Rules and Strategies?

### ISSUE THREAD

**Issue by team172011** [mdeverdelhan/ta4j#127]
During several runs with different parameters and strategies, it would be very nice to have such a standard method that returns as string all rules of a strategy or all parameters of a rule.

**Comment by TheCookieLab** [comment]
Returning all rules/params of a strategy can become very verbose very quickly. Can you get away with just adding "name" and "description" String member variables (should be final) to the Strategy class?

**Comment by mdeverdelhan** [comment]
Yes, very verbose. You may also have a look to the logging feature: https://github.com/mdeverdelhan/ta4j/wiki/Usage%20examples#logging

**Comment by team172011** [comment]
I did not noticed this feature so far, it looks very usefull for our intends to analyse several strategies at once. Thank you for the hint.
