### ISSUE TITLE
Is there a way to implement Stochastic RSI

### ISSUE THREAD

**Issue by imthegod** [mdeverdelhan/ta4j#132]
I want to use stochastic RSI for my trading strategy. After going through the code, I cannot find any direct method to do that. I can modify and add a new calculate function but I don't want to do that unless required.Can someone guide me if it is there? If not, I will develop it.

**Comment by gcauchis** [comment]
Hello,
It may be something like that:
```java
// Stoch RSI = (RSI - MinimumRSIn) / (MaximumRSIn - MinimumRSIn)
int n = 10;
RSIIndicator rsi = new RSIIndicator(new ClosePriceIndicator(data), n);
LowestValueIndicator minRsi = new LowestValueIndicator(rsi, n);
HighestValueIndicator maxRsi = new HighestValueIndicator(rsi, n);
        
int tickIndex = 12;// your index
Decimal value = rsi.getValue(tickIndex).minus(minRsi.getValue(tickIndex)).dividedBy(maxRsi.getValue(tickIndex).minus(minRsi.getValue(tickIndex)));
```

**Comment by mdeverdelhan** [comment]
Hi!

Thank you @gcauchis :)
Feel free to make a PR if you want to get this added.
