### ISSUE TITLE
How to consider dividend or swap rate etc in ta4j

### ISSUE THREAD

**Issue by hotpeperoncino** [mdeverdelhan/ta4j#133]
I'm interested in totalreturn of investment. so income gain like dividend or swap rate at fxtrade is important factor. I cannot find how to treat then by ta4j. Can I have information?

**Comment by ElMoe** [comment]
Hi,
there’s a a way to calculate the total return and an 'Annualized Total Return‘ with:
https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/statistics/PeriodicalGrowthRateIndicator.java

If you want to consider dividends you have to take the performance prices of a stock for the calculation. 
I have plans to add something to take fees etc. into the calculation, but i am quite busy at the moment.

Bastian

**Comment by mdeverdelhan** [comment]
Dividends and stuff of that kind are not managed by ta4j.

**Comment by hotpeperoncino** [comment]
Thank you for your reply!
