### ISSUE TITLE
Define Filter Interface for the Strategies

### ISSUE THREAD

**Issue by enkara** [mdeverdelhan/ta4j#137]
Hello,
First of all thank you for this great tool. It surely saves a lot of time using this library as a starting point. 
So far I have seen, you can identify a Strategy by Entry and Exit-Rules. What about having a further constructor where you can define a filter. A filter in this case means before the entry rules apply you want make sure that the security the strategy is applied for confirms further conditions. As an example you want that the underlying instrument is liquid enough or belongs to a certain index. Or you want the check your account first. I hope you get the idea.  

Thank you and best wishes,

**Comment by mdeverdelhan** [comment]
It seems it is just another kind of rules. You can combine them with logicial operators and thus you can short-circuit the relevant ones if your NotEnoughMoneyOnMyAccoutRule returns true.

**Comment by enkara** [comment]
The big difference between a filter and the standard rule is the possibility excluding trading canditates being triggered at all. Of course the rule definition would work but would not reduce the trading canditetes at all.
Thanks,

**Comment by mdeverdelhan** [comment]
I do not get you. If you do something like:
`new YourFilteringRule().and(new YourRealRule())`

For the i-th tick, if `YourFilteringRule` returns false, `YourRealRule` will not be evaluated. This i-th tick will not be in the trading candidates.
