### ISSUE TITLE
better caching support

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#138]
"ta4j" uses its own "caching system". Would be nice, if you can be replace "ta4j-caching" by official Java Caching (JCache) "JSR 107". Java provides internal support for caching. 

With this, we can bridge "java-cache" with something like "redis" https://mvnrepository.com/artifact/com.github.mrniko/redis-jcache or other providers easily and store large "timeseries" without the issue of setMaximumTickCount(int) or the like (CachedIndicator..)

**Comment by nimo23** [comment]
I guess, there is no need for that as we can store timeseries and load it within ta4j without needing ta4j.

**Comment by nimo23** [comment]
According to https://github.com/mdeverdelhan/ta4j/issues/72 @mdeverdelhan said:

"Moreover I have in mind to refactor the caching system to let the advanced user choose the underlying cache mechanism (i.e. no cache, basic arraylist cache, DB cache, etc.)..."

If there are any plans for this, it would make sense to use "JSR107 caching" instead of actual caching implementation. With "standard caching" bridges to other stores (memory, persistent) are easier to achieve.

**Comment by mdeverdelhan** [comment]
Still in my mind, but not enough time. :/
Of course we will try to be compliant with the JSR.

**Comment by nimo23** [comment]
Actually, only tick-data is stored in a cache. However, would be nice to have "caching capability" of "trading record", too. So we can plug in database layer to store all the trading records (for example, of one week).

**Comment by mdeverdelhan** [comment]
Please continue this thread on the new repo: https://github.com/ta4j/ta4j
