### ISSUE TITLE
calculate hashCode with "Objects.hash()"

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#140]
Hello,

a minor thing:

Instead of

```
@Override
    public int hashCode() {
        return (entry.hashCode() * 31) + (exit.hashCode() * 17);
    }
```

you can calculate "hashCode" in your codebase with java build in method "Objects.hash()";

```
@Override
	public int hashCode() {
		return Objects.hash(entry, exit);
	}
```

It is easier and makes the code looks clear;)

**Comment by mdeverdelhan** [comment]
AFAIK, not available in Java 6.

**Comment by mdeverdelhan** [comment]
I am still hesitating. See my comment about Java 8: https://github.com/mdeverdelhan/ta4j/issues/93#issuecomment-225697165
