### ISSUE TITLE
ChaikinMoneyFlowIndicator

### ISSUE THREAD

**Issue by SergeyZYX** [mdeverdelhan/ta4j#142]
Tried to use ChaikinMoneyFlowIndicator(14) on WTI futures data from Quandl and found out gaps:

![chaik](https://cloud.githubusercontent.com/assets/28604810/26187222/4547b316-3ba8-11e7-928c-cc54125af23a.png)

OHLCV (2009-03-20,51.556,52.602,50.86,51.868,163397.4) = 0.21483617272294842
OHLCV (2009-03-23,52.13,54.05,51.62,53.8,229890.0) = 0.220560912295664
OHLCV (2009-03-24,53.83,54.2,52.45,53.98,212790.0) = 0.19622175756695917
OHLCV (2009-03-25,53.73,54.18,51.86,52.77,283727.0) = 0.20621706970653647
OHLCV (2009-03-26,52.84,54.66,52.76,54.34,196916.0) = 0.21041174980358116
OHLCV (2009-03-27,54.0,54.28,51.64,52.38,181165.0) = 0.1888587339287318
OHLCV (2009-03-30,52.25,52.25,48.11,48.41,222171.0) = 0.2009217137558275
OHLCV (2009-03-31,48.64,50.0,47.77,49.66,240254.0) = 0.35813238062169545
OHLCV (2009-04-01,48.96,48.96,47.26,48.39,234224.0) = 0.2965932845899256
OHLCV (2009-04-02,48.45,52.87,48.45,52.64,270270.0) = 0.40674044855541536
OHLCV (2009-04-03,52.36,53.9,51.02,52.51,212172.0) = 0.3444921018656213
OHLCV (2009-04-06,52.4,53.6,49.81,51.05,228983.0) = 0.2743862311177961
OHLCV (2009-04-07,51.39,51.82,48.4,49.15,254031.0) = 0.17441382122286686
OHLCV (2009-04-08,48.47,51.3,47.37,49.38,352611.0) = 0.13629812241059033
OHLCV (2009-04-09,49.96,52.45,49.72,52.24,294835.0) = 0.19659626697649885
OHLCV (2009-04-13,52.0,52.15,48.84,50.05,290456.0) = 0.11814331435094565
OHLCV (2009-04-14,49.96,51.12,48.85,49.41,284710.0) = 0.03016374982900696
OHLCV (2009-04-15,49.16,50.79,48.91,49.25,228056.0) = 0.006461712129088827
OHLCV (2009-04-16,50.202,50.984,49.608,50.416,187772.6) = -0.0216211167819643
OHLCV (2009-04-17,50.758,52.106,50.302,51.186,147673.0) = 3.994585025716414E-4
OHLCV (2009-04-20,51.42,51.57,47.09,47.458,189016.8) = 0.009776004395794612
OHLCV (2009-04-21,47.644,48.872,46.142,48.142,248319.0) = -0.005284241769906233
OHLCV (2009-04-22,48.68,49.09,47.7,48.85,238729.0) = 0.017809782775359016
OHLCV (2009-04-23,48.49,49.92,48.37,49.62,227296.0) = -0.012345840436732312
OHLCV (2009-04-24,49.65,51.75,49.06,51.55,230865.0) = 0.043304956636592666
OHLCV (2009-04-27,51.45,51.45,48.01,50.14,265293.0) = 0.08424303302229079
OHLCV (2009-04-28,50.1,50.19,48.55,49.92,186823.0) = 0.1653660658891755
OHLCV (2009-04-29,49.25,51.42,49.12,50.97,234826.0) = 0.21278719529737736
OHLCV (2009-04-30,50.79,51.94,50.21,51.12,208296.0) = 0.14327455764464483
OHLCV (2009-05-01,50.95,53.65,50.43,53.2,248750.0) = 0.22749132874470507
OHLCV (2009-05-04,52.62,54.64,52.56,54.47,229782.0) = 0.341101539870671
OHLCV (2009-05-05,54.46,54.83,53.5,53.84,234306.0) = 0.35049975228487285
OHLCV (2009-05-06,54.12,56.47,53.57,56.34,334302.0) = 0.41880050836932375
OHLCV (2009-05-07,56.3,58.57,55.46,56.71,377826.0) = 0.37029796459876113
OHLCV (2009-05-08,56.5,58.75,56.15,58.63,291819.0) = 0.4784659041996046
OHLCV (2009-05-11,58.49,58.63,56.78,58.5,290030.0) = 0.5100844580526647
OHLCV (2009-05-12,58.1,60.08,57.81,58.85,305957.0) = 0.45111533133656867
OHLCV (2009-05-13,59.29,59.9,57.41,58.02,311802.0) = 0.361407807609118
OHLCV (2009-05-14,57.884,59.084,56.94,58.78,235719.6) = 0.3535749939990562
OHLCV (2009-05-15,58.564,58.768,56.442,56.604,195036.6) = 0.29760453824486094
OHLCV (2009-05-18,57.928,59.486,57.638,59.366,187260.2) = 0.3077796324942861
OHLCV (2009-05-19,59.592,60.176,59.47,60.01,229110.0) = 0.3023969070784397
OHLCV (2009-05-20,60.8,62.04,60.8,62.04,270022.0) = 0.36667747487822916
OHLCV (2009-05-21,60.1,61.05,60.1,61.05,237412.0) = 0.38339044063202565
OHLCV (2009-05-22,61.67,61.67,61.67,61.67,186302.0) = NaN
OHLCV (2009-05-26,59.8,62.45,59.8,62.45,267127.0) = NaN
OHLCV (2009-05-27,63.0,63.45,62.85,63.45,261888.0) = NaN
OHLCV (2009-05-28,63.56,65.35,63.56,65.08,281439.0) = NaN
OHLCV (2009-05-29,65.68,66.31,65.4,66.31,261370.0) = NaN
OHLCV (2009-06-01,67.73,68.58,67.73,68.58,234080.0) = NaN
OHLCV (2009-06-02,68.55,68.65,68.35,68.55,266861.0) = NaN
OHLCV (2009-06-03,67.8,67.8,65.45,66.12,322365.0) = NaN
OHLCV (2009-06-04,67.65,69.25,67.65,68.81,304674.0) = NaN
OHLCV (2009-06-05,68.49,69.05,68.02,68.44,329259.0) = NaN
OHLCV (2009-06-08,67.95,68.88,67.95,68.09,289278.0) = NaN
OHLCV (2009-06-09,69.67,70.01,69.1,70.01,316884.0) = NaN
OHLCV (2009-06-10,70.9,71.55,70.55,71.33,346248.0) = NaN
OHLCV (2009-06-11,72.14,72.92,72.14,72.68,314790.0) = NaN
OHLCV (2009-06-12,71.9,72.04,71.9,72.04,224601.0) = 0.4730439853072078
OHLCV (2009-06-15,70.0,70.62,69.76,70.62,242211.0) = 0.46975824783963177
OHLCV (2009-06-16,72.75,72.75,70.47,70.47,266350.0) = 0.3371883209316747
OHLCV (2009-06-17,69.84,71.222,69.58,71.164,242088.6) = 0.34772060311844577
OHLCV (2009-06-18,71.018,71.802,70.748,71.586,167492.2) = 0.31413435971406983
OHLCV (2009-06-19,71.068,71.65,69.46,69.832,208920.8) = 0.21936094599380054
OHLCV (2009-06-22,69.52,69.69,66.686,67.386,245916.8) = 0.1629193495696546
OHLCV (2009-06-23,67.15,69.68,66.37,69.24,279901.0) = 0.2557980517708237
OHLCV (2009-06-24,68.55,69.86,68.06,68.67,242855.0) = 0.20211110467242885
OHLCV (2009-06-25,68.29,70.93,68.11,70.23,254942.0) = 0.2581532867478829
OHLCV (2009-06-26,70.34,71.29,68.81,69.16,254942.0) = 0.2659315094490548
OHLCV (2009-06-29,69.25,71.92,68.36,71.49,229882.0) = 0.23202240461763549
OHLCV (2009-06-30,71.6,73.38,68.9,69.89,331550.0) = 0.12493227937606308
OHLCV (2009-07-01,70.45,71.85,68.52,69.31,331550.0) = 0.04051903933245649
OHLCV (2009-07-02,69.22,69.74,66.26,66.73,243250.0) = -0.07323536035647343
OHLCV (2009-07-06,65.54,65.65,63.4,64.05,256986.0) = -0.17154035734764853
OHLCV (2009-07-07,64.19,64.91,62.21,62.93,262358.0) = -0.13122338086390598
OHLCV (2009-07-08,62.31,62.68,60.01,60.14,334958.0) = -0.2725316541076109
OHLCV (2009-07-09,60.38,61.62,59.25,60.41,314800.0) = -0.2897584410523704
OHLCV (2009-07-10,60.45,60.89,58.72,59.89,50.0) = -0.26815462264201256
OHLCV (2009-07-13,59.86,60.67,58.32,59.69,301907.0) = -0.2141903624232025
OHLCV (2009-07-14,60.14,61.46,59.15,59.52,305947.0) = -0.325441860939894
OHLCV (2009-07-15,59.79,62.0,59.65,61.54,279729.0) = -0.25509830855323284
OHLCV (2009-07-16,62.196,62.446,60.522,62.228,231697.0) = -0.24289943486943366
OHLCV (2009-07-17,62.584,64.394,61.46,63.968,188528.2) = -0.15969531974853035
OHLCV (2009-07-20,63.974,65.5,63.796,64.766,202881.0) = -0.20167916571306657
OHLCV (2009-07-21,65.128,66.45,64.398,65.432,248696.8) = -0.15308375951644654
OHLCV (2009-07-22,65.03,65.77,63.76,65.4,319989.0) = -0.045788737204932387
OHLCV (2009-07-23,65.4,67.49,64.4,67.16,321627.0) = 0.07579237525116406
OHLCV (2009-07-24,66.62,68.2,66.46,68.05,217270.0) = 0.15831047219774366
OHLCV (2009-07-27,68.05,68.99,67.6,68.38,245180.0) = 0.2024686710757698
OHLCV (2009-07-28,68.26,68.86,66.48,67.23,253558.0) = 0.2680508274142101
OHLCV (2009-07-29,66.68,67.01,62.7,63.35,342411.0) = 0.1987074563522279
OHLCV (2009-07-30,62.86,67.29,62.76,66.94,344216.0) = 0.2572392305859707
OHLCV (2009-07-31,66.69,69.74,64.96,69.45,400836.0) = 0.32812768220463523
OHLCV (2009-08-03,69.3,71.95,69.09,71.58,323455.0) = 0.44086968427470064
OHLCV (2009-08-04,71.34,71.95,70.16,71.42,285877.0) = 0.4265195457287551
OHLCV (2009-08-05,71.82,72.1,69.71,71.97,307551.0) = 0.44214855846816575
OHLCV (2009-08-06,71.83,72.42,70.18,71.94,328670.0) = 0.44023319901655555
OHLCV (2009-08-07,71.81,72.84,70.38,70.93,367023.0) = 0.36981030393084097
OHLCV (2009-08-10,70.67,71.57,70.09,70.6,304092.0) = 0.3430000055154837
OHLCV (2009-08-11,70.76,71.25,68.71,69.45,389079.0) = 0.2553752914846883
OHLCV (2009-08-12,69.67,71.13,68.84,70.16,342269.0) = 0.20912342738951795
OHLCV (2009-08-13,70.54,72.21,70.05,70.52,322969.0) = 0.12478816693493407
OHLCV (2009-08-14,70.9,71.6,67.12,67.51,320144.0) = 0.05921487890049628
OHLCV (2009-08-17,68.092,68.108,65.668,67.162,240473.0) = 0.09137187062876645
OHLCV (2009-08-18,67.604,70.966,66.842,69.95,203825.2) = 0.1706468170171508
OHLCV (2009-08-19,71.24,73.706,69.088,73.266,276795.4) = 0.15807704379183338
OHLCV (2009-08-20,73.27,73.832,72.354,72.836,218518.0) = 0.06367936080775419
OHLCV (2009-08-21,72.88,74.72,72.03,73.89,246228.0) = 0.029836815910027837
OHLCV (2009-08-24,73.75,74.81,73.57,74.37,208702.0) = 0.016664909630323244
OHLCV (2009-08-25,73.97,75.0,71.11,72.05,324399.0) = -0.09131804630877267
OHLCV (2009-08-26,71.35,72.64,70.67,71.43,255501.0) = -0.15421733592646605
OHLCV (2009-08-27,71.36,72.95,69.83,72.49,272730.0) = -0.05724797018992386
OHLCV (2009-08-28,72.86,73.52,71.78,72.74,239217.0) = -0.027319918804055918
OHLCV (2009-08-31,71.0,73.36,69.13,69.96,276967.0) = -0.02971187021316551
OHLCV (2009-09-01,69.85,71.37,68.0,68.05,336835.0) = -0.13104300625576917
OHLCV (2009-09-02,67.7,68.8,67.05,68.05,269497.0) = -0.07307013949296379
OHLCV (2009-09-03,68.15,69.4,67.66,67.96,231967.0) = -0.04364389804917693
OHLCV (2009-09-04,68.19,69.7,67.12,68.02,229782.0) = -0.07815926995381965
OHLCV (2009-09-08,67.87,71.79,67.54,71.1,374237.0) = -0.03491870905524156
OHLCV (2009-09-09,71.33,72.52,70.66,71.31,331984.0) = -0.1193073608314838
OHLCV (2009-09-10,71.64,72.44,70.86,71.94,345551.0) = -0.06402858563910101
OHLCV (2009-09-11,72.05,72.9,68.82,69.29,374693.0) = -0.15597754147030543
OHLCV (2009-09-14,69.15,69.51,68.02,68.86,255720.0) = -0.16099044740486634
OHLCV (2009-09-15,68.78,71.19,68.48,70.93,288040.0) = -0.06435466718150126
OHLCV (2009-09-16,70.4,72.56,70.14,72.51,291946.0) = 0.018329714593047497
OHLCV (2009-09-17,72.39,73.244,71.754,72.564,218096.4) = -0.02405637934557706
OHLCV (2009-09-18,72.588,72.844,71.446,72.22,150988.4) = -0.02673941749135954
OHLCV (2009-09-21,72.038,72.47,69.146,69.842,230410.4) = -0.018314011385064156
OHLCV (2009-09-22,69.75,71.994,69.714,71.718,203204.2) = 0.10770951461483665
OHLCV (2009-09-23,71.63,71.81,68.04,68.97,307578.0) = 0.05595685854020825
OHLCV (2009-09-24,68.33,68.77,65.6,65.89,357456.0) = 0.018808071518345366
OHLCV (2009-09-25,65.92,67.09,65.05,66.02,315319.0) = 0.03176245544810096
OHLCV (2009-09-28,66.15,67.54,65.41,66.84,231410.0) = -0.011511974070428305
OHLCV (2009-09-29,67.11,67.33,65.82,66.71,247345.0) = 0.02599828305730066
OHLCV (2009-09-30,66.71,70.72,66.22,70.61,247345.0) = 0.05582928088157199
OHLCV (2009-10-01,70.4,71.39,69.13,70.82,312014.0) = 0.17792607653258943
OHLCV (2009-10-02,70.35,70.69,68.32,69.95,334690.0) = 0.19907950136491115
OHLCV (2009-10-05,69.81,71.0,68.05,70.41,346922.0) = 0.18950322454683916
OHLCV (2009-10-06,70.26,71.97,70.06,70.88,346922.0) = 0.10135569628253552
OHLCV (2009-10-07,71.16,71.76,68.88,69.57,346922.0) = 0.047875011471094436
OHLCV (2009-10-08,69.8,72.55,69.17,71.69,405214.0) = 0.08818895297813964
OHLCV (2009-10-09,71.42,72.35,70.62,71.77,322276.0) = 0.14183595255442472
OHLCV (2009-10-12,72.24,73.84,72.05,73.27,260226.0) = 0.12640801334189591
OHLCV (2009-10-13,73.17,74.55,72.83,74.15,361151.0) = 0.20357013684551375
OHLCV (2009-10-14,74.4,75.53,74.4,75.18,296006.0) = 0.298957767007501
OHLCV (2009-10-15,75.444,78.066,74.886,77.68,333149.4) = 0.35870782447838956
OHLCV (2009-10-16,77.96,78.934,77.024,78.726,228763.0) = 0.3816240694953711
OHLCV (2009-10-19,78.896,79.906,78.29,79.82,206086.4) = 0.41742919799823125
OHLCV (2009-10-20,79.906,80.33,78.266,79.114,282864.4) = 0.3488692018862402
OHLCV (2009-10-21,78.69,82.0,77.64,81.37,395742.0) = 0.37070513245476655
OHLCV (2009-10-22,81.04,81.5,79.86,81.19,295407.0) = 0.3871034158965728
OHLCV (2009-10-23,80.55,80.55,80.5,80.5,293751.0) = 0.2770739947385201
OHLCV (2009-10-26,79.65,81.58,77.97,78.68,363907.0) = 0.23689872515571944
OHLCV (2009-10-27,78.68,79.89,77.81,79.55,375672.0) = 0.3334401462984261
OHLCV (2009-10-28,79.47,79.83,77.06,77.46,359438.0) = 0.23299845739935804
OHLCV (2009-10-29,78.75,80.46,77.03,79.87,360575.0) = 0.2605146513585216
OHLCV (2009-10-30,79.98,80.21,76.85,77.0,412394.0) = 0.1488561521168257
OHLCV (2009-11-02,77.02,78.66,76.56,78.13,371006.0) = 0.1464725384508522
OHLCV (2009-11-03,78.09,79.77,76.55,79.6,373992.0) = 0.19170171032153083
OHLCV (2009-11-04,79.47,81.06,79.12,80.4,366103.0) = 0.16148490840310584
OHLCV (2009-11-05,80.29,80.52,79.34,79.62,257603.0) = 0.09383332871383991
OHLCV (2009-11-06,79.8,80.34,76.71,77.43,379374.0) = 0.006004929778111053
OHLCV (2009-11-09,79.2,80.19,77.77,79.43,327402.0) = 0.04086179498571751
OHLCV (2009-11-10,79.24,80.51,77.89,79.05,371088.0) = -0.024924416253529445
OHLCV (2009-11-11,78.88,80.1,78.57,79.28,297815.0) = -0.06669126958008954
OHLCV (2009-11-12,79.25,79.69,76.52,76.94,412833.0) = -0.06703844927129654
OHLCV (2009-11-13,76.78,77.67,75.57,76.35,335366.0) = -0.04051931299979889
OHLCV (2009-11-16,76.58,79.43,76.35,78.9,361387.0) = -0.0438125705247634
OHLCV (2009-11-17,79.04,79.85,78.262,79.256,284090.6) = 0.02213845512138068
OHLCV (2009-11-18,79.576,80.55,78.894,79.788,227374.8) = -0.022956480723686137
OHLCV (2009-11-19,79.948,80.188,77.39,77.814,256538.4) = 0.01884533032404186
OHLCV (2009-11-20,78.246,78.486,76.648,77.32,245480.6) = -0.03616446626118428
OHLCV (2009-11-23,77.8,79.92,77.15,77.56,382888.0) = -0.1701659135785275
OHLCV (2009-11-24,77.45,77.8,75.6,76.02,413033.0) = -0.2502018785264089
OHLCV (2009-11-25,75.83,78.09,75.5,77.96,337389.0) = -0.15114590142246725
OHLCV (2009-11-27,77.29,77.94,72.39,76.05,301347.0) = -0.08237381118991073
OHLCV (2009-11-30,76.05,78.0,75.13,77.28,358538.0) = -0.06940851073485638
OHLCV (2009-12-01,77.35,79.04,77.01,78.37,310483.0) = -0.03762243384726115
OHLCV (2009-12-02,77.9,78.59,76.22,76.6,340897.0) = -0.08327996954884716
OHLCV (2009-12-03,76.51,77.5,75.54,76.46,351788.0) = -0.02185519800618399
OHLCV (2009-12-04,75.83,77.9,74.85,75.47,411579.0) = -0.05597090074835923
OHLCV (2009-12-07,75.8,76.1,73.7,73.93,359248.0) = -0.1711341629610336
OHLCV (2009-12-08,74.0,74.39,72.51,72.62,424771.0) = -0.2606313297294129
OHLCV (2009-12-09,73.12,73.87,70.13,70.67,526968.0) = -0.32333584820418504
OHLCV (2009-12-10,70.8,71.39,69.81,70.54,407657.0) = -0.2853067271206263
OHLCV (2009-12-11,70.57,71.2,69.46,69.87,407657.0) = -0.30467120751900023
OHLCV (2009-12-14,69.63,70.22,68.59,69.51,268931.0) = -0.2530513864565499
OHLCV (2009-12-15,69.57,71.15,69.31,70.69,262945.0) = -0.1842528869859971
OHLCV (2009-12-16,70.78,73.55,70.59,72.66,298377.0) = -0.2223672241951744
OHLCV (2009-12-17,73.094,73.498,71.55,72.936,181961.4) = -0.23166796967695447
OHLCV (2009-12-18,73.072,75.074,72.95,73.784,185160.6) = -0.28623514377774434
OHLCV (2009-12-21,73.574,74.224,72.802,73.22,162567.2) = -0.3330416415738343
OHLCV (2009-12-22,73.214,74.468,72.626,74.03,182012.2) = -0.2711868192700353
OHLCV (2009-12-23,74.52,77.0,74.25,76.67,196830.0) = -0.24099827474082605
OHLCV (2009-12-24,76.59,78.25,76.19,78.05,102484.0) = -0.17739728171088276
OHLCV (2009-12-28,77.92,79.12,77.76,78.77,108895.0) = -0.0970074785758427
OHLCV (2009-12-29,78.66,79.39,78.02,78.87,137090.0) = 0.013846669687822978
OHLCV (2009-12-30,78.8,79.8,78.46,79.28,137090.0) = 0.1490216816445053
OHLCV (2009-12-31,79.28,80.0,79.16,79.36,120372.0) = 0.15291686129042834
OHLCV (2010-01-04,79.63,81.79,79.63,81.51,263542.0) = 0.3188501358860866
OHLCV (2010-01-05,81.77,81.77,81.77,81.77,258887.0) = NaN
OHLCV (2010-01-06,81.43,83.52,80.85,83.18,370059.0) = NaN
OHLCV (2010-01-07,83.2,83.36,82.26,82.66,246632.0) = NaN
OHLCV (2010-01-08,82.65,83.47,81.8,82.75,310377.0) = NaN
OHLCV (2010-01-11,82.88,83.95,81.96,82.52,296304.0) = NaN
OHLCV (2010-01-12,82.07,82.34,79.91,80.79,333866.0) = NaN
OHLCV (2010-01-13,80.06,80.67,78.37,79.65,401627.0) = NaN
OHLCV (2010-01-14,79.698,80.438,79.0,79.488,364670.6) = NaN
OHLCV (2010-01-15,79.2,79.31,77.7,78.0,200555.0) = NaN
OHLCV (2010-01-19,78.066,79.342,76.94,79.2,285417.6) = NaN
OHLCV (2010-01-20,79.112,79.294,77.208,77.716,280382.8) = NaN
OHLCV (2010-01-21,77.56,78.36,75.66,76.08,327417.0) = NaN
OHLCV (2010-01-22,75.84,76.5,74.01,74.54,348819.0) = NaN
OHLCV (2010-01-25,74.24,75.42,74.06,75.26,280559.0) = NaN
OHLCV (2010-01-26,75.28,75.39,73.82,74.71,256207.0) = -0.05509931939336778
OHLCV (2010-01-27,74.69,75.09,72.65,73.67,356179.0) = -0.13319806672710813
OHLCV (2010-01-28,73.75,74.49,72.93,73.64,292911.0) = -0.12232436746026415
OHLCV (2010-01-29,73.89,74.82,72.43,72.89,335270.0) = -0.178724177217225
OHLCV (2010-02-01,72.84,74.99,72.49,74.43,277411.0) = -0.11438983255247308
OHLCV (2010-02-02,74.94,77.41,74.4,77.23,366269.0) = -0.018767503358198875

**Comment by mdeverdelhan** [comment]
Explanation with this sequence:

> OHLCV (2009-05-22,61.67,61.67,61.67,61.67,186302.0) = NaN
> OHLCV (2009-05-26,59.8,62.45,59.8,62.45,267127.0) = NaN
> OHLCV (2009-05-27,63.0,63.45,62.85,63.45,261888.0) = NaN
> OHLCV (2009-05-28,63.56,65.35,63.56,65.08,281439.0) = NaN
> OHLCV (2009-05-29,65.68,66.31,65.4,66.31,261370.0) = NaN
> OHLCV (2009-06-01,67.73,68.58,67.73,68.58,234080.0) = NaN
> OHLCV (2009-06-02,68.55,68.65,68.35,68.55,266861.0) = NaN
> OHLCV (2009-06-03,67.8,67.8,65.45,66.12,322365.0) = NaN
> OHLCV (2009-06-04,67.65,69.25,67.65,68.81,304674.0) = NaN
> OHLCV (2009-06-05,68.49,69.05,68.02,68.44,329259.0) = NaN
> OHLCV (2009-06-08,67.95,68.88,67.95,68.09,289278.0) = NaN
> OHLCV (2009-06-09,69.67,70.01,69.1,70.01,316884.0) = NaN
> OHLCV (2009-06-10,70.9,71.55,70.55,71.33,346248.0) = NaN
> OHLCV (2009-06-11,72.14,72.92,72.14,72.68,314790.0) = NaN

On first tick (2009-05-22) you have the max price which is equal to the min price. The `CloseLocationValueIndicator` formula has a division by (maxPrice-minPrice). It gives (61.67 - 61.67) == 0, which turns into a division by zero.
=> Here comes a first NaN.

Then all derived calculations return NaN (because NaN + XXX - YYY * ZZZ / ... == NaN). And specifically:
  * The current Chaikin calculation
  * The next 13 Chaikin calculation (because you asked for Chaikin(14), which means that Chaikin(n) needs Chaikin(n-13), Chaikin(n-12), Chaikin(n-11), ... to be calculated)

Same explanation for the other NaN sequence.
