### ISSUE TITLE
Order of referecing tick data 

### ISSUE THREAD

**Issue by enkara** [mdeverdelhan/ta4j#144]
Hi,

I use the work with MultiCharts and Tradestation as trading platform. 
One thing I like very much on this platforms is if you reference to tick data 0 reference to the latest available bar.
E.g. on a daily bar it would be like: close[0] means the close price from today and close[10] references to the close price 10 days ago. 
This approach is very intuitive and easy to understand and it enables also the compare the values of the indicators. Usually
Everyone is interested to the latest available data.

When I look to the TimeSeries the first tick timeSeries.getTick(0) returns the oldest data. If one uses the other way, you have
always make sure that you are indexing the latest tick data.
I have recently started to working with this library and it might be that I haven’t understood yet. Am I getting it wrong? What do you think about it?

Thank you

**Comment by TheCookieLab** [comment]
I would prefer the existing way as it's consistent with Java list behavior. Changing it to resemble some vendor specific notation is a bad idea.

**Comment by team172011** [comment]
I think there is no need for a discussion about this. This kind of indexing is absolute standard in every comparable data structure in java. If you want to get the last element use something like code[code.length] or regarding a Tick from TimeSeries : serie.getTick(serie.getTickCount()-1)

**Comment by mdeverdelhan** [comment]
Same comment as previous. I like the idea but not for a Java lib, much more for a trading platform.

**Comment by enkara** [comment]
Fair enough. Thanks.
