### ISSUE TITLE
"getAllTicks()" from TimeSeries is missing

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#149]
Please provide a convenient method to get all the ticks of a TimeSeries. Something like:

**TimeSeries#getTicks()**

```
public class TimeSeries {
..
/** List of ticks */
    private final List<Tick> ticks;
..

// Please provide this method
public List<Tick> getTicks(){
		return this.ticks;
}
..
```
}

**Comment by nimo23** [comment]
I added PR:

https://github.com/mdeverdelhan/ta4j/pull/150

**Comment by mdeverdelhan** [comment]
Rejected. It introduces an ambiguity when using subseries. See also: https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeries.java#L276
