### ISSUE TITLE
AnalysisCriterion for absolute profit

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#151]
I have put my enter-amount and exit-amount in my trading record:

```
if (s.shouldEnter(i)) {
		        // Entering...
		        tradingRecord.enter(i, t.getClosePrice(), Decimal.valueOf(10));
		    } else if (s.shouldExit(i)) {
		        // Exiting...
		        tradingRecord.exiti(i, t.getClosePrice(), Decimal.valueOf(10));
		    }
```

Now I want to see my actual profit for the series:

```
AnalysisCriterion totalProfit = new TotalProfitCriterion();
 log.info("Our profit: {}", totalProfit.calculate(series, tradingRecord));
```

However, the number is something like "1.0451072450484816". What does this mean (percentage)? Can I view my absolute profit? Something like:

` (("exitPrice of last sell order").minus("entryPrice of last buy order")).multiply.("amount of last sell order")`

If not, would be nice to provide a new "AnalysisCriterion" for such cases.

**Comment by team172011** [comment]
If you take a look at the `calculate(TimeSeries series, TradingRecord tradingRecord) ` function you can see that it calculates the total percentage of profit/loss over all trades based on 1. So `1.045` means that you will have a total profit of 4,5% of your starting capital. The amount is not taken into account, it is (just?) stored in the corresponding orders of the trading record. 
[At the moment](https://github.com/mdeverdelhan/ta4j/issues/5#issuecomment-47429856) the TradingRecord class is not just a class that records the trades based on the underlying strategy of the TimeSerie, but it decideds that you can just be invested (enter) or not (exit). It is not possible to [buy more](https://github.com/mdeverdelhan/ta4j/issues/114) or open another trade. As far as i have understood your amount per trade doess not matter, it is always the same. If you multiply your amount (that is in this case your starting capital) with the total percentage profit you get your absolute profit

**Comment by nimo23** [comment]
Ok. Thanks. So there is no need for a new AnalyisCriterion.

**Comment by nimo23** [comment]
However
