### ISSUE TITLE
make "calculateProfit for one single trade"

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#152]
I want to calculate my profit of each single trade. There is no method like this:

For example: "TotalProfitCriterion" calculates the profit of trade1:

```
AnalysisCriterion totalProfit = new TotalProfitCriterion();
 log.info("Our profit: {}", trade1.calculate(totalProfit));
```

**Comment by mdeverdelhan** [comment]
It already exists if I remember well. `new TotalProfitCriterion().calculate(series, trade);`

**Comment by nimo23** [comment]
ok, thanks!
