### ISSUE TITLE
provide method "getDateTime" of Trade#Order

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#154]
Please provide a method getDateTime() for a Order so we can have something like this:

```
// DateTime when "Order-Entry" occured
trade.getEntry().getDateTime();

// DateTime when "Order-Exit" occured
trade.getExit().getDateTime();
```

Thanks.

**Comment by mdeverdelhan** [comment]
`series.getTick(trade.getEntry().getIndex()).getBeginTime();` and `series.getTick(trade.getEntry().getIndex()).getEndTime();`?

**Comment by nimo23** [comment]
ok. thanks!
