### ISSUE TITLE
Support "TrailingStopLossRule"

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#156]
Actually, when "StopLossRule" is triggered, then a BUY is made. However, would be nice to provide a new Rule called **"TrailingStopLossRule"** which changes the StopLoss to a percentage (threshold) of the upper price, record this (in the TradingRecord) and triggers a BUY only if this threshold is fullfilled. For example:

```
// if price goes higher (new Price), then adapt the StopLoss, so StopLoss would only be triggered,
// if (newPrice*0.8) is reached in the future
Rule trailStopLoss = new TrailingStopLossRule(closePrice, Decimal.valueOf("0.8"));
```

`price 1.2 (stop loss=0.96) -> price 1.4 (stop loss=1.12) -> price 1.0 (Rule "trailStopLoss" is fullfilled, hence trigger Sell-Signal)
`
Please provide "TrailingStopLossRule". Thanks.

**Comment by team172011** [comment]
I have written such a similar rule some weeks ago. It is based on the close price of the previous tick, but you can change it to high/low of the previos tick to get some kind of trailling stop rule:

`import eu.verdelhan.ta4j.Decimal;
import eu.verdelhan.ta4j.Trade;
import eu.verdelhan.ta4j.TradingRecord;
import eu.verdelhan.ta4j.indicators.simple.ClosePriceIndicator;
import eu.verdelhan.ta4j.trading.rules.AbstractRule;

public class BuyTrailingStopRule extends AbstractRule{
		
    /** The close price indicator */
    private ClosePriceIndicator closePrice;
    
    /** The loss ratio threshold (e.g. 0.97 for 3%) */
    private Decimal lossRatioThreshold;
    
    /**
     * Constructor.
     * @param closePrice the close price indicator
     * @param lossPercentage the loss percentage
     */
    public BuyTrailingStopRule(ClosePriceIndicator closePrice, Decimal lossPercentage) {
        this.closePrice = closePrice;
        this.lossRatioThreshold = Decimal.HUNDRED.minus(lossPercentage).dividedBy(Decimal.HUNDRED);
    }
    
    /**
     * returns true if the current price is lower than the
     * previous price reduced by threshold
     */
    
	@Override
	public boolean isSatisfied(int index, TradingRecord tradingRecord) {
        boolean satisfied = false;
        // No trading history or no trade opened, no loss
        if (tradingRecord != null) {
            Trade currentTrade = tradingRecord.getCurrentTrade();
            if (currentTrade.isOpened()) {
                Decimal previusPrice = closePrice.getValue(Math.max(0,index-1));
                Decimal currentPrice = closePrice.getValue(index);
                satisfied = currentPrice.isLessThanOrEqual(previusPrice.multipliedBy(lossRatioThreshold));
            }
        }
        traceIsSatisfied(index, satisfied);
        return satisfied;
	}
}`

**Comment by nimo23** [comment]
Thanks. This is exactly what I meant.

Why not making a PR (but rename the method to "TrailingStopLossRule") ?

**Comment by nimo23** [comment]
I guess, making such a rule is not so common. So I am in doubt to make a PR. If someone think it is a good idea, then reopen the issue.

**Comment by nimo23** [comment]
According to https://github.com/mdeverdelhan/ta4j/issues/61 and https://github.com/mdeverdelhan/ta4j/pull/63, it seems the "TrailingStopLossIndicator" is already within ta4j. However, I cannot find it. Does anyone knows where it is?

**Comment by ElMoe** [comment]
>  I cannot find it. Does anyone knows where it is?
> 

You can google to find it: „ta4j trailingstoplossindicator“. It is in „trackers“:
https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/trackers/TrailingStopLossIndicator.java

Regards,
Bastian
