### ISSUE TITLE
Tick: There is no way to set the amount field besides adding trades

### ISSUE THREAD

**Issue by karvanit** [mdeverdelhan/ta4j#162]
When a new Tick is created we can set initial values for all fields except `amount` and `trades`.
There is currently no way to set the values of these fields except through the `.addTrade()` function. This is not good enough, since we *can* know these values when we construct a full Tick from historical data.

So we need a constructor that can (at least) accept both `amount` and `volume`.

**Comment by mdeverdelhan** [comment]
OK. Make a PR with those initial values and some tests and I will merge it.
