### ISSUE TITLE
Question Community for Strategies

### ISSUE THREAD

**Issue by madwicket** [mdeverdelhan/ta4j#163]
I was wondering if there was a community or forum where everyone shares there own strategies?

**Comment by team172011** [comment]
I do not think that there is an appreciable platform. It would be nice to have some kind of repository were people can present and discuss their strategies.

**Comment by TheCookieLab** [comment]
You know what they say, "_be the change you want to see in the world_". 

If you want such a community/forum, why not start one?

**Comment by team172011** [comment]
I am not an expert for git repositories but we could start here: 
https://github.com/team172011/ta4j-strategies

Next week i will start to implement some basic strategies and share them there

**Comment by mdeverdelhan** [comment]
@team172011 You can add your repo in this page: https://github.com/mdeverdelhan/ta4j/wiki/Related%20projects

**Comment by team172011** [comment]
Okay, i will do so after some more commits
