### ISSUE TITLE
Creating rules without having any timeseries

### ISSUE THREAD

**Issue by sirilicious** [mdeverdelhan/ta4j#164]
First of all, great lib!

I was wondering if I can create the entry and exit rules for my strategy without knowing any timeseries? e.g. the `ClosePriceIndicator` needs a `timeSeries` upon creation - can it just grab the timeseries, wich I specify when actually run the strategy? `TradingRecord tradingRecord = timeSeries.run(strategy);`

Thanks!

**Comment by mdeverdelhan** [comment]
You can create an empty `TimeSeries` object and feed it with data later.

**Comment by martinklepsch** [comment]
This can probably be closed?

**Comment by sirilicious** [comment]
yes thanks
