### ISSUE TITLE
WaitForRule gets never satisfied without initial Order

### ISSUE THREAD

**Issue by quorak** [mdeverdelhan/ta4j#165]
hey there,

thanks for this great lib. Just stumbled upon this issue. Even thought the commen `No trading history, no need to wait` indicates other intention, the WaitForRule gets never satisfied without an initial Order.

Is this Intended? Makes backtesting quite hard. 
If not its probably a quick change from `false` to `true` in 
https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/trading/rules/WaitForRule.java#L54

thanks again,
best

**Comment by mdeverdelhan** [comment]
It is intended. Here is the class documentation:
```
 * A {@link Rule rule} which waits for a number of {@link Tick ticks} after an order.
 * <p>
 * Satisfied after a fixed number of ticks since the last order.
```

But you are right: the "No trading history, no need to wait" comment is confusing and should be something like "No trading history, no initial event to wait after".

Could you give an example of in which way it makes your backtesting hard?

**Comment by quorak** [comment]
Well, lets assume you have a set of Rules to execute your Trading Strategies, all rules should be satisfied so the strategy would make a buy decision. I start the Backtesting.

With the waitForRule beeing part of it. There would never be an initial Trade, so there would never be a Trade History, thus my Strategy can never do a buy decision.

e.g.:
```
       Rule entryRule = new OverIndicatorRule(sslr, Decimal.valueOf(0.003 * 1.5))
                .and(new OverIndicatorRule(closePrice,shortEma))
                .and(new OverIndicatorRule(closePrice,longEma))
                .and(new WaitForRule(Order.OrderType.BUY,minutes_9H));

```

I would have to add a Or Rule that checks for an empty Trading History to make the strategy work. Not sure it this is intended. I changed the initial `satisified` to `true` in 
https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/trading/rules/WaitForRule.java#L54 to make my usecase work.

does this make sense? It is is intended. we can close the ticket. hope it helps. thanks again. best

**Comment by mdeverdelhan** [comment]
OK I see. Your use case makes sense. But changing the initial `satisfied` to `true` may lead to unwanted side-effects (and for me it would be weird to not to wait if you don't have any order).

I would prefer something like:
```
Rule entryRule = new OverIndicatorRule(sslr, Decimal.valueOf(0.003 * 1.5))
                .and(new OverIndicatorRule(closePrice,shortEma))
                .and(new OverIndicatorRule(closePrice,longEma))
                .and(new SatisfiedOnEmptyHistoryRule().or(new WaitForRule(Order.OrderType.BUY,minutes_9H)));
```

Maybe we could add this SatisfiedOnEmptyHistoryRule. Don't hesitate to implement it.

**Comment by mdeverdelhan** [comment]
Please continue this thread on the new repo: https://github.com/ta4j/ta4j
