### ISSUE TITLE
feeding ticks into a moving time series

### ISSUE THREAD

**Issue by erikvoit** [mdeverdelhan/ta4j#166]
I have just started experimenting with this library and I am hoping you an clarify for me something about feeding ticks into a TimeSeries(String name, org.joda.time.Period timePeriod) with the addTick() method?

I am wondering about feeding uniform length ticks ex. 10 seconds in to time series of different Periods. I don't even see this TimeSeries(String name, org.joda.time.Period timePeriod)  constructor in the source code?  

I've used the above constructor to define three time periods of 10 seconds, 1 minute, and 5 minutes.

new TimeSeries("fast_series", Period.seconds(10));
new TimeSeries("mid_series", Period.minutes(1));
new TimeSeries("slow_series", Period.minutes(5));

I am feeding them all the same live tick data every 10 seconds:
new Tick(DateTime.now(), openPrice, highPrice, lowPrice, closePrice, volume);

Each series returns the same getTickCount() but a SMAIndicator() set to the same time frame does appear to be returning different values.  Is the TimeSeries doing the work of coalescing 6 addTicks into one period of the mid_series?  Where is the above constructor in the source code? Am I missing something here or otherwise losing data points by feeding my time series in this way?

**Comment by mdeverdelhan** [comment]
> Is the TimeSeries doing the work of coalescing 6 addTicks into one period of the mid_series?

Not at all. The constructor you are looking for does not exist. You have to build your 10sec ticks, 1m ticks and 5m ticks by yourself. Then you create 3 time series and you feed each one of them with one of your 3 tick lists.

**Comment by erikvoit** [comment]
While I agree I can't find the constructor in the TimeSeries.java class file you do make reference to it in the wiki here:
https://github.com/mdeverdelhan/ta4j/wiki/Time%20series%20and%20ticks

> Time series for live trading

Live trading involves building a time series for current prices. In this use case you just have to initialize your series with a time interval.

TimeSeries series = new TimeSeries("my_live_series", Period.days(1));

And as I said that constructor does appear to work in my code.  How is this possible?  

I am adding ticks to my time series like this:
Tick newTick = new Tick(DateTime.now(), openPrice, highPrice, lowPrice, closePrice, volume);

Thank you for the response.  I didn't see there was a similar question already asked a few months ago.  At any rate I have since rewritten my logic so that there is a separate timer constructing ticks and adding them to each various length time series via myTimeSeries.addTick(newTick);

**Comment by mdeverdelhan** [comment]
The constructor has been removed in 0.9-SNAPSHOT. The documentation is still for the 0.8.
