### ISSUE TITLE
RSI Value is different using this lib in comparison with manual calculation of RSI using the formula 

### ISSUE THREAD

**Issue by s-kiips** [mdeverdelhan/ta4j#167]
i used this class to get list of close price. From the API i get the LIST of one year close price as well as open, high, low, volume, and date.
[apidataclass.txt](https://github.com/mdeverdelhan/ta4j/files/1213750/apidataclass.txt)

I used this second class to calculate all the indicators.. the other indicator value seems all correct but the value of RSI is incorrect.
[calculationclass.txt](https://github.com/mdeverdelhan/ta4j/files/1213759/calculationclass.txt)

This is the Json output from the API that is in the apidataclass.txt file
[API-Json-Output.zip](https://github.com/mdeverdelhan/ta4j/files/1213786/API-Json-Output.zip)

**Comment by mdeverdelhan** [comment]
See #90.
