### ISSUE TITLE
Consider making a release

### ISSUE THREAD

**Issue by martinklepsch** [mdeverdelhan/ta4j#169]
Using SNAPSHOTS is generally somewhat dangerous (as they might change without explicit action) and currently the API docs may also be outdated. There also have been several commits since the 0.8 release so I guess it would be nice to package these up properly as well.

**Comment by mdeverdelhan** [comment]
I will think about it. There were not many changes since the 0.8.

**Comment by martinklepsch** [comment]
Why do there have to be many changes to justify a release? :o)

Just up to date docs would already be great. Especially with the java.time
changes...

**Comment by mdeverdelhan** [comment]
Done!
