### ISSUE TITLE
StopLossRule and StopGainRule just refer to long positioning?

### ISSUE THREAD

**Issue by team172011** [mdeverdelhan/ta4j#170]
As far as i could see, the two Rules `StopLossRule` and `StoppGainRule` are satisfied if the current price is lower or higher than the given percentage value of the entry price.
If you are going to build a short strategie you have to use them "reverse" and the label "...gainRule" or "...lossRule" are incorrect identifiers.

Would it make sense to rename those rules or to implement the possibility to pass an additional parameter like `Order.Type type` to get expected behaviour in both kinds of strategy?

**Comment by nimo23** [comment]
Maybe that's the reason for https://github.com/mdeverdelhan/ta4j/issues/153 ?

Because for "StopGainRule" TradingRecord does not go "short".
