### ISSUE TITLE
Questions about Tick#addTrade()

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#173]
I have a TimeSeries with a Period of 1 hour.

For example:

```
- Tick_1 (endTime 14:00 p.m.)
- Tick_2 (endTime: 15:00 p.m.)
```

Between these two ticks, I get the latest bid/ask every minute:

```
...
latest price : 1.31$ at 14:03 p.m.
ask: 1.32$ (volume: 12) at 14:03 p.m.
bid: 1.35$ (volume: 15) at 14:03 p.m.
...
latest price : 1.313$ at 14:04 p.m.
ask: 1.31$ (volume: 10) at 14:04 p.m.
bid: 1.32$ (volume: 18) at 14:04 p.m.
...
```

According to https://github.com/mdeverdelhan/ta4j/issues/72, I can put one of these values into the related Tick. 

```
// Tick_1.addTrade(tradeAmount, tradePrice); 
Tick_1.addTrade(12, 1.32);
Tick_1.addTrade(10, 1.31);
```

**I have the following questions:**

1. Should I put the "ask-value/volume" into addTrade() ?
2. Why can I not put the "date value" within the addTrade()-Method? With this we can make near-realtime-calculations such as volatility (https://github.com/mdeverdelhan/ta4j/issues/177).
3. When I put aks-values to "addTrade()" into the latest tick, does the next call of  "shouldEnter/shouldBuy" consider these values? (Will the calculation of the last tick considers these values coming from addTrade())?

**Comment by mdeverdelhan** [comment]
1. Using Ta4j you can't.
  2. Because the only relevant date is the tick time (i.e. the end time of the preceding period). Volatility should be calculated using aggregated data (i.e. tic info).
  3. No, because you  can't.

**Comment by nimo23** [comment]
I know, I can add a Trade by **recorder.enter/exit**. So for what exactly is **series#tick#addTrade()** ?

**Comment by mdeverdelhan** [comment]
Again it is a naming problem. The addTrade() method is used to "feed" a Tick (i.e. to update its values with a trade from your broker/exchange/whatever). The Trade object we have in ta4j is a pair of two of your orders when running your strategy.

**Comment by nimo23** [comment]
So the "addTrade()" is the same as the the "Trade" we put into recorder.enter/exit ?

**Comment by mdeverdelhan** [comment]
No they are different.
  * "addTrade()" helps you building your Ticks.
  * the Trade object corresponds to the Orders you execute when running your Strategy

**Comment by nimo23** [comment]
Does ta4j **uses the information** provided by tic.addTrade() in any way? 

I know, the trading record is for recording (and analyzing) the made trades. And tick#addTrade is for what? Could you please give me an example when to make use of the information in tick#addTrade()?

**Comment by mdeverdelhan** [comment]
See this example: https://github.com/mdeverdelhan/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/loaders/CsvTradesLoader.java#L96

**Comment by nimo23** [comment]
Sorry but I really dont find any sense for Tick#addTrade. 

**Ta4j does not make use of this information in any way, am I right?**

For what I see, the tick#addTrade only holds information about MY trades made by the broker but is not stored in a TradingRecord. So when I want to store AND analyze my trades then I need to store it in TradingRecord. So for what tick#addTrade()?

**Comment by mdeverdelhan** [comment]
You are wrong.
The addTrade(...) method does not hold anything. BUT, you can use it to build the Ticks of a TimeSeries. In such case, you give it the information about ALL the trades (a.k.a. executed market orders) made by the broker (and NOT only yours).

It is confusing because both Trade concepts are not the same.
  * In the addTrade(...) method you put this information: someone sold XXX shares for a unit price of YYY
  * In a TradingRecord Trade you store one of YOUR pairs of entry/exit

Both may be called "Trade" but they are different things. I don't know how to explain it by other means.

**Comment by nimo23** [comment]
Thank you. Now it is clear. I understand:) **The "addTrade()" is for the "Market Sales".** This is cool. With "Market Sales" price propagation can be done (such as **"Tape Reading"**). Would be nice to include such a  strategy to analyze the Market Sales. For example, higher sales in volume and price leads to ... But this includes to store the Market Sales within "addTrade()" so we can build a ta4j-Strategy for it. Would it be worth?

**Comment by nimo23** [comment]
**Maybe the "addTrade()"-Method could be renamed into "addMarketSale()".** It s better, dont you think so? Because a Trade consists of Buy and Sale. But in the "Market Sale" we only log the "Sale". So "addMarketSale()" is exactly the name which should be used.

**Comment by mdeverdelhan** [comment]
A "sale" for someone is a "purchase" for another one. "Trade" is a neutral word.

Please continue this thread on the new repo: https://github.com/ta4j/ta4j
