### ISSUE TITLE
Question: Use buy order price in sell strategy

### ISSUE THREAD

**Issue by wardloockx** [mdeverdelhan/ta4j#174]
Hello,

Is there a way to get the buy price in the build Strategy function?

I want to create my selling strategy based on my the price of the buy order.

Can't seem to figure out a way on how to do that.

Thanks,
W.

**Comment by team172011** [comment]
You could write some kinde of `OverEntryPriceRule` that is satisfied if there is an open trade and if its entry price (= Buy if long) is greater than a specific threshold you gave as parameter (not tested):

`
 public class OverEntryPriceRule extends AbstractRule{

        private Indicator<Decimal> indicator;
        private Decimal threshold;

        public OverEntryPriceRule(Indicator<Decimal> indicator, Decimal threshold){
            this.indicator = indicator;
            this.threshold = threshold;
        }
        
        
        @Override
        public boolean isSatisfied(int i, TradingRecord tradingRecord) {
            if (tradingRecord.getCurrentTrade().isOpened()){
                return tradingRecord.getCurrentTrade().getEntry().getPrice().isGreaterThanOrEqual(threshold);
            }
            return false;
        }
    }
`

**Comment by mdeverdelhan** [comment]
Same answer than @team172011
