### ISSUE TITLE
Is there a need for something like PreviousValueIndicator?

### ISSUE THREAD

**Issue by team172011** [mdeverdelhan/ta4j#175]
At the moment there is a `PreviousPriceIndicator` that returns the previous close price of the time series, but there are no indicators for the previous min, max or open price. I think to receive previous values  (not just regarding prices) is an important thing for building a strategy.

Because of that, I want to discuss if there is a need for an indicator that returns the previous value of another indicator. For an application I have written a similar indicator that returns the nth value of another indicator:

`PreviousValueIndicator(Indicator<E>, n)`

So for example the previous open price would be:
`PreviousValueIndicator prevOpen = new PreviousValueIndicator(openPriceIndicator, 1)`

Or the value of an ema indicator two tick ago:
`PreviousValueIndicator prevEMA = new PreviousValueIndicator(emaIndicator, 2)`

Does such an indicator make sense and is needed or did I not notice another way to get those values?

**Comment by mdeverdelhan** [comment]
What about `indicator.getValue(index - 1);`?

**Comment by team172011** [comment]
I think this does not work while building a strategy. 

E.g. how could i define a rule that is satisfied if close price is higher than previous ticks max price?

**Comment by mdeverdelhan** [comment]
Hum I see. Ok for your `PreviousValueIndicator(Indicator<E>, n)`. Please make a PR. Don't forget to document it and add unit tests.

**Comment by mdeverdelhan** [comment]
Added in #185
