### ISSUE TITLE
date-field within a Trade-Object

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#177]
Please provide a new field "date" (LocalDateTime) within a "Order-Object". With this we can make "TradingRecord"-Analysis such as "duration between two trades" (buy-sell). I know, we can get the date by using timeseries, however, if a tick of timeseries is not available anymore (for example by maxTickCount), then there is no way to determine the date of a trade.

**Comment by martinklepsch** [comment]
@nimo23 a `Trade` object consists of two `Order` objects which each have an index which connects them to a `TimeSeries`. Using the index stored in each `Order` you can retrieve the `Tick` inside the `TimeSeries` which will have a timestamp.

**Comment by nimo23** [comment]
okay, I edited it to "within a "Order-Object". The same problem here: for analyis we need "date" within a Order, because if linking to series is broken (for example by "maxTickCount"), then no date is available.

**Comment by martinklepsch** [comment]
I see, that makes sense. 👍

**Comment by nimo23** [comment]
https://github.com/mdeverdelhan/ta4j/issues/178

**Comment by mdeverdelhan** [comment]
Please continue this thread on the new repo: https://github.com/ta4j/ta4j
