### ISSUE TITLE
addTrade bad calculation

### ISSUE THREAD

**Issue by smartdeath** [mdeverdelhan/ta4j#183]
**I have a problem with Tick model.**
`addTrade `method has 2 parameters `(tradeAmount,tradePrice)`
`volume` property should be summed with tradeAmount and
amount parameter should be combined with the result of `tradeAmount*tradePrice`.

this code is for `Tick` model in  `addTrade` method 
```
this.amount = this.amount.plus(tradeAmount);
this.volume = this.volume.plus(tradeAmount.multipliedBy(tradePrice));
```

I think this code is not true.
Please help me.Thank you.

**Comment by mdeverdelhan** [comment]
Wow! Nice one! They should be inverted. I will try to fix this soon.
