### ISSUE TITLE
Clarifying meaning of 'Tick'

### ISSUE THREAD

**Issue by magick93** [mdeverdelhan/ta4j#184]
Hi

Correct me if I am wrong, but it seams that ta4j considers a tick to have a time span, eg a tick of 1 minute in length - is this correct?

> A Tick contains aggregated data of a security/commodity during a time period.

Usually, especially in forex trading, an aggregation of price changes for a period of time is a Bar, eg, the min, max, first and last (OHLC) for one minute. During this minute there can be 100s of ticks.

Does ta4j have the concept of bars also? 

What is the reason for giving ticks a time span?

**Comment by martinklepsch** [comment]
There is an issue with discussion about this question already, I think you
can find it if you search issues for "bar" or so.

**Comment by team172011** [comment]
If you take a closer look to the `Tick` class you can find out that a tick describes some kind of bar. There are among others close, min, max, and open price attributes. The 'time span' describes the time span for that this attributes are valid. You can but not have to give ticks a time span, you just have to give at least an end time for each tick.

**Comment by martinklepsch** [comment]
I added a note to the wiki noting this difference: https://github.com/mdeverdelhan/ta4j/wiki/Time-series-and-ticks

**Comment by martinklepsch** [comment]
(I guess this issue should be closed to keep discussion focused in #139.)

**Comment by mdeverdelhan** [comment]
Duplicate of #139
