### ISSUE TITLE
aroon indicator calculation

### ISSUE THREAD

**Issue by rrphotosoft** [mdeverdelhan/ta4j#187]
Hi,
Aroon indicator calculation produces unexpected result:
Consider this timeseries

```
TimeSeries ts = new TimeSeries();
for(int i = 0; i < 100; i ++){
	ZonedDateTime zdt = ZonedDateTime.now().plusDays(i);
	Tick t = new Tick(zdt, Decimal.valueOf("NaN"),Decimal.valueOf("NaN"),Decimal.valueOf("NaN"),Decimal.valueOf("NaN"),Decimal.valueOf("NaN"));
	ts.addTick(t);
}
```
Attempting to calculate a 25 day aroon up indicator:

```
AroonUpIndicator aru = new AroonUpIndicator(ts, 25);
for(int i = 0; i  < 100; i++){
    System.out.println(String.valueOf(i) + ":" + std.getValue(i));
}
```
It prints 0 for every tick.
A value of 0 in aroon terminology is generally a __strong bearish__ sign. 
A similarly unexpected result is noted on RSI (built on the close price indicator), with the value being 100 on every tick, and zero on the first tick.

Could you please add your thoughts on this.

Best Regards,
RR.

**Comment by mdeverdelhan** [comment]
Sorry but no. You are in a limit case.
Reading the code and debugging, try to find out in which way the calculations are incorrect AND if a change would be relevant. Do not hesitate to make a pull request if you are able to fix those indicators.

**Comment by rrphotosoft** [comment]
Hi,
Thanks for you reply, I will get back to you with a pull request.
Best Regards,
RR.

**Comment by dpalic** [comment]
@rrphotosoft do you have any updates on this issue?
Since this repository was dropped, we have moved to a new organisation. See #192
Could you please repost your question there, if it is still needed? https://github.com/ta4j/ta4j
If not, could you do me a favour and close this issue here?

**Comment by rrphotosoft** [comment]
Hi,
Unfortunately the issue cannot be closed. The indicator is calculated even when null values are provided for the prices. 
I am working on refactoring the relevant code , but it is complicated.
I will need more time, perhaps till the end of september.
@dpalic

**Comment by team172011** [comment]
@rrphotosoft please continue this discussion on the [new repository](https://github.com/ta4j/ta4j). You can also open a new issue  and make a pull-request to the `develop `branch

**Comment by mdeverdelhan** [comment]
Closed. @rrphotosoft Please make your future PR in the new repository https://github.com/ta4j/ta4j. (and good luck)
