### ISSUE TITLE
addTick with "open", "high", "low" optional ?

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#188]
When I am using only the **ClosePriceIndicator for all strategies**, do I need the "open", "high" and "low"-price? 

Are there indicators which need also the open, high and low prices for internal calculations? 

**Will the calculation of indicators be wrong when I feed my tick with one price "series.addTick(close, close, close, close)" instead of "series.addTick(open, high, low, close)".**

**Comment by rrphotosoft** [comment]
Yes this will erroneously calculate some indicators, when they would have actually been incalculable. Eg: stochastic oscillator indicator[see definition]
What you are suggesting would be dangerous.

**Comment by nimo23** [comment]
There are indicators which does not make use of o,h,l such as momentum.

**Comment by rrphotosoft** [comment]
In that case why not initialize with series.addTick(NaN, NaN, NaN close), that way there is no chance of something going wrong.

**Comment by nimo23** [comment]
hmm...but **what if "ohlc"-values are really the same** because the tick comes from a timeseries with a period of one second or below. **So the duration of each tick is "one second" and the ohlc-values does not change within one second or below.** Then the calculation of all indicators are okay, am I right?

**Comment by nimo23** [comment]
okay.. series.addTick(NaN, NaN, NaN close) is a good idea. thanks!
