### ISSUE TITLE
strategy not decoupled from tradingrecord

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#189]
When using **strategy.shouldEnter(index)** and **strategy.shouldExit(index)** with a timeseries and **without a trading-record**, the strategy.shouldEnter(index) works as expected, but the **"strategy.shouldExit(index)"** will be never true even though the strategy for exit should be called because of its exit-rule. 

 When using **strategy.shouldEnter(index, _recorder_)** and **strategy.shouldExit(index, _recorder_)** **with** a trading-record, then all works (enter AND exit signals will happen). 

**But why do I need a trading-record to get my Exit-Signals?** 

The Strategy should fire up exit-signals as well without a trading-record because all what the strategy needs is its related timeseries. Why is strategy-execution not decoupled from trading-record ?

**Comment by nimo23** [comment]
By the way, this is the reason: for https://github.com/mdeverdelhan/ta4j/issues/153

**Comment by team172011** [comment]
There are cases where you need the TradingRecord for exit or entry signal. For example if you use the waitForRule or all other cases where your signals depend on orders or your trade history

**Comment by team172011** [comment]
`strategy.shouldEnter(index) `and `strategy.shouldExit(index)` are overloaded and do nothing more than call `shouldEnter(index, (TradingRecord)null);`

If your strategy is based on rules that need a TradingRecord than they will mostly return false if TradingRecord is null or empty. For example the WaitForRule:
```
 public boolean isSatisfied(int index, TradingRecord tradingRecord) {
        boolean satisfied = false;
        if (tradingRecord != null) {
            Order lastOrder = tradingRecord.getLastOrder(this.orderType);
            if (lastOrder != null) {
                int currentNumberOfTicks = index - lastOrder.getIndex();
                satisfied = currentNumberOfTicks >= this.numberOfTicks;
            }
        }

        this.traceIsSatisfied(index, satisfied);
        return satisfied;
    }
```

Same with StopLossRule:

```
public boolean isSatisfied(int index, TradingRecord tradingRecord) {
        boolean satisfied = false;
        if (tradingRecord != null) {
            Trade currentTrade = tradingRecord.getCurrentTrade();
            if (currentTrade.isOpened()) {
                Decimal entryPrice = currentTrade.getEntry().getPrice();
                Decimal currentPrice = (Decimal)this.closePrice.getValue(index);
                Decimal threshold = entryPrice.multipliedBy(this.lossRatioThreshold);
                if (currentTrade.getEntry().isBuy()) {
                    satisfied = currentPrice.isLessThanOrEqual(threshold);
                } else {
                    satisfied = currentPrice.isGreaterThanOrEqual(threshold);
                }
            }
        }

        this.traceIsSatisfied(index, satisfied);
        return satisfied;
    }
```

So what rules are you using? I think in your case without TradingRecodr your exit rule gets never satisfied becaus` (TradingRecord != null) -> FALSE`...

**Comment by nimo23** [comment]
Yes, you are right, (TradingRecord != null) -> FALSE is the reason for no "EXIT".

In my case, exit rule is "stopgain"-rule.  However, the API does not inform, which exit/enter rules needs a trading-record and which does not. So it's a little confusing. And the other thing: why does the exit is not fired without trading-record. ta4j has the timeseries and with the timeseries it could be calculated when to enter and when to exit. When not using a trading-record, ta4j can give a bunch of enter-signals and in relation to this it could give the exit-signal. But this does not work. Why?

**Comment by team172011** [comment]
I do not understand your question, what do you mean with: 

> ta4j can give a bunch of preceeding enter-signals

 this could be the TradingRecord?

If you take a strategy for long positioning, the `StopGainRule` needs to **know the entry price** of the `currentTrade`. This information is stored in the `TradingRecord`. How else should the rule know if the price has climbed up enough to exit??

**Comment by nimo23** [comment]
ta4j can give a bunch of preceeding enter-signals:

when iterating through the ticks  and loop through the ticks with shouldEnter/shouldExit then the result could be this:

```
1, 8,13 €  -> [ ENTER ]
2, 8,11 € -> 
3, 8,13 € -> 
4, 8,11 €  -> [ ENTER ]
5,12 €  -> 
6, 8,11 €  -> 
7, 8,14 €  -> 
8,15 €  -> 
```

You see **2 Enter-signals fired on index 1 and 4**. And no exit signal (because series.shouldExit/Enter has no tradingrecord associated). 

`How else should the rule know if the price has climbed up enough to exit??`

However, even when there is no trading-record, ta4j could decide the EXIT by the last ENTER. So for example, index 8 should be fired by strategy.shouldExit, because the preceding ENTER has all the information about the possible last enter-price. So for example, stop-gain could be fired because it has all the information within the timeseries (without needing a tradingrecord). 

Maybe I am wrong with that?

**Comment by team172011** [comment]
You are right with that, but i think this could be very inefficient. In worst case each rule has to re-check each previous ticks or not?

**Comment by nimo23** [comment]
yes, faster with tradingrecord. So it is better to use tradingrecord.
