### ISSUE TITLE
Performance enhancements?

### ISSUE THREAD

**Issue by dan-lind** [mdeverdelhan/ta4j#19]
Just wondering if you are aware of any possible performance improvements that could be implemented, but that you haven't had time to look into yet? 
I haven't looked in detail into the new code using TADecimal, and I haven't performed any detailed measurements, but it when backtesting multiple strategies at once it feels like the cost of improved accuracy is a severe decrease in performance overall.

**Comment by mdeverdelhan** [comment]
I created a more specific issue for performance enhancements around the Decimal class (as other solutions have been either implemented or ruled out). See #28.
