### ISSUE TITLE
CrossUpIndicator/CrossDownIndicator

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#191]
I dont understand the "CrossUpIndicator/CrossDownIndicator":

```
    public CrossedUpIndicatorRule(Indicator<Decimal> first, Indicator<Decimal> second) {
        this.cross = new CrossIndicator(second, first);
    }
```

When I use this
`
Rule r1 = new CrossedUpIndicatorRule(fastIndicator, slowIndicator);`

does this mean:

Rule is satisfied when the "fastIndicator" **crosses over** the "slowIndicator".

When I use this
`
Rule r2 = new CrossedDownIndicatorRule(fastIndicator, slowIndicator);`

does this mean:

Rule is satisfied when the "fastIndicator" **crosses down** the "slowIndicator".

Am I right with r1 and r2?

**Comment by team172011** [comment]
yes

**Comment by team172011** [comment]
you can also use just one indicator type to express both statements if you swap the two parameters.

**Comment by nimo23** [comment]
The code of "CrossIndicator":

```
 if (up.getValue(i).isGreaterThan(low.getValue(i))) {
            return true;
```

returns true, if "up" is greater than "down".

However, the  "CrossedUpIndicatorRule" swaps the parameters. So second will be the "up" and first will be the "low".

```
public CrossedUpIndicatorRule(Indicator<Decimal> first, Indicator<Decimal> second) {
        this.cross = new CrossIndicator(second, first);
    }
```

So this means, second crosses up the first?

**Comment by nimo23** [comment]
Okay, I understand.

This is the same:

```
// true, as long as a-value is or will be come higher than b-value
Rule r = new CrossedUpIndicatorRule(a, b);

// true, as long as a-value is or will become higher than b-value
Rule r = new CrossIndicator(b, a)

// true, as long as a-value is or will become higher than b-value
Rule r = new CrossedDownIndicatorRule(b, a);
```

Maybe we should put this into javadoc?

**Comment by team172011** [comment]
`Rule r = new CrossIndicator(b, a)`  You cannot assign an indicator to a rule^^

**Comment by nimo23** [comment]
yes, I correct it.

**Comment by nimo23** [comment]
What is the difference of "CrossedUpIndicatorRule" and "OverIndicatorRule" ?

**Comment by nimo23** [comment]
What is the difference of "CrossedUpIndicatorRule" and "OverIndicatorRule" ?

**Comment by team172011** [comment]
CrossedUpIndicatorRule is satisfied if a crossed b.  That means in tick i-1 a < b and in tick i a > b. In Tick i+1 if a is still ober b the rule wont be satisfied

OverIndicatorRule is satisfied if a is over be, always if a >b..

**Comment by nimo23** [comment]
Okay this makes sense. Thanks. 

So OverRule is **always satisfied** for a  if a>b. 
But if I use CrossedUpRule for a, then it is only **one time satisifed** if a>b.

**Comment by team172011** [comment]
Yes, it is only one time satisfied if a has crossed b between tick i and tick i-1.
