### ISSUE TITLE
New Double Top/Double Bottom indicator should be added. 

### ISSUE THREAD

**Issue by puneet739** [mdeverdelhan/ta4j#193]
I think doubletop/bottom indicator should be added. It gives a lot of positive or negative signal. 

This can be taken as future enhancement.

**Comment by team172011** [comment]
Do you have a definition? As far as i could find out it will be rather less an indicator than an rule or strategie.

**Comment by puneet739** [comment]
It can be seen as part of strategy.. ie it can be rule
For more indepth info you can check
http://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:chart_patterns:double_bottom_reversal

I am not able to create even a psuedo code for the same hence asked someone
with more info. if you can generate a technical blue print and guide i can
try to create implementation of the same.


Regards
Puneet Behl
0-9711616135

**Comment by team172011** [comment]
It is not a basic rule nether a basic indicator, i think than there is no need for this in this library?

**Comment by puneet739** [comment]
Dont know. But this occurence is seen in combination with multiple indicators. 
If this will be added it increases the probability of positive trade order. If you consider that this is not required this can be skipped but you should keep this in consideration for future tests. 

Rest its your call.

**Comment by TheCookieLab** [comment]
Would be pretty easy to implement given 90% of the code is already written in the HighestValueIndicator.

**Comment by puneet739** [comment]
@TheCookieLab  I was trying to implement the same. But failed at below points. We use openValue or close value indicator at times. If i use open or close it wont come near the value. 

Also the top can varry in some percentage difference and not exact price. How to handle that. Any suggestion/advice would be great. I will try to create the code and add a pull request. Once on finding it right you can add that indicator. But i would require your advice. Kindly suggest how to proceed.

**Comment by dpalic** [comment]
@puneet739 could you close this issue here? Since we have moved the discussion to the new organisation

**Comment by mdeverdelhan** [comment]
Transfered to https://github.com/ta4j/ta4j/issues/3
