### ISSUE TITLE
New Renko Charts

### ISSUE THREAD

**Issue by puneet739** [mdeverdelhan/ta4j#195]
We can add new renko charts for new analysis
http://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:renko

**Comment by dpalic** [comment]
hello Puneet,
could you please reask your question in the newly maintained repository.
This repository was dropped See #192 
Please repost your question there https://github.com/ta4j/ta4j-transition ?

**Comment by mdeverdelhan** [comment]
Transfered to https://github.com/ta4j/ta4j/issues/2
