### ISSUE TITLE
Momentum Indicator?

### ISSUE THREAD

**Issue by nimo23** [mdeverdelhan/ta4j#196]
I need a typical Price Momentum Indicator (https://en.wikipedia.org/wiki/Momentum_(technical_analysis)). 

I cannot find it in the ta4j-API with such name. Does it exist?

**Comment by team172011** [comment]
what about:

```
int n = 10;
ClosePriceIndicator cp = new ClosePriceIndicator(series);
DifferenceIndicator momentum = new DifferenceIndicator(cp, new PreviousValueIndicator(cp,n));
```

**Comment by nimo23** [comment]
Thank you. For a typical Price-Momentum-Indicator, the actual momentum should be a relative number, where the number oscillates around 0 (=100%). 

**I want to make a PR, so do you find anything to better this?:**

public class MomentumIndicator extends CachedIndicator<Decimal> {

    private final int timeFrame;
    
    private final Indicator<Decimal> indicator;
    
```
    public MomentumIndicator(Indicator<Decimal> indicator, int timeFrame) {
        super(indicator);
        this.indicator = indicator;
        this.timeFrame = timeFrame;
    }

    @Override
    protected Decimal calculate(int index) {
    	
    	PreviousValueIndicator prev = new PreviousValueIndicator(indicator, timeFrame);
    	DifferenceIndicator momentum = new DifferenceIndicator(indicator, prev);
    	
    	Decimal prevVal = prev.getValue(index-timeFrame);
        Decimal momentumVal = momentum.getValue(index);

        return momentumVal.dividedBy(prevVal)
                .multipliedBy(Decimal.HUNDRED);
    }
}
```

**Comment by team172011** [comment]
Looks good. But regarding #192 PR will not be merged.

**Comment by nimo23** [comment]
Okay, no need for that. Because ta4j already has such a momentum-indicator called "ROCIndicator".
