### ISSUE TITLE
RSI Divide by zero issue

### ISSUE THREAD

**Issue by viper161616** [mdeverdelhan/ta4j#27]
Hi,

Perhaps I'm misunderstanding how to use things here, but when I do the following:

```
closePriceIndicator = new ClosePriceIndicator(timeSeries);
rsiIndicator = new RSIIndicator(closePriceIndicator, 5);
```

Then proceed to call "getValue();"  I get:
```
rsiIndicator.getValue(0); // 0;
rsiIndicator.getValue(1); // Divide by zero exception.
```

The data in my closePriceIndicator is fine and works as expected. I'm expecting values between 0 and 100 that correspond to the RSI Values at the respective dates.

I'm using the jar from maven central: ta4j-0.5

Thanks!

**Comment by mdeverdelhan** [comment]
Hi,

Already noticed in #16. I recommend you to use the 0.6-SNAPSHOT.

Anyway thank you for using ta4j. :)
