### ISSUE TITLE
'Rule' not found

### ISSUE THREAD

**Issue by rrphotosoft** [mdeverdelhan/ta4j#38]
Hi
I have added ta4j 0.6 maven repository to my pom file as follows:

   <dependency>
			<groupId>eu.verdelhan</groupId>
			<artifactId>ta4j</artifactId>
			<version>0.6</version>
  </dependency>

Unfortunately the 
"eu.verdelhan.ta4j.trading" package is not found.
Can you please help me?

Also I have never used sonatype before, can you tell me exactly what lines to paste into my pom file so that I can use your latest snapshot(in case that is the reason for the above error)/

Regards,
RR.

**Comment by mdeverdelhan** [comment]
Hi and thank you for your interest,

Indeed, you are trying to use features which are not released yet. Use the 0.7-SNAPSHOT to get them. Your `pom.xml` should look like this:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    	<modelVersion>4.0.0</modelVersion>
    	<groupId>test.test</groupId>
    	<artifactId>test</artifactId>
    	<version>0.0.1-SNAPSHOT</version>
    
    	<repositories>
    		<repository>
    			<id>sonatype snapshots</id>
     			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
    		</repository>
    	</repositories>
    
    	<dependencies>
    		<dependency>
    			<groupId>eu.verdelhan</groupId>
    			<artifactId>ta4j</artifactId>
    			<version>0.7-SNAPSHOT</version>
    		</dependency>
    	</dependencies>
    
    </project>

Regards,

Marc

**Comment by rrphotosoft** [comment]
Hi Marc,
Thanks for the reply, I got it working!
Regards,
RR.
