### ISSUE TITLE
Possible update for TimeSeries.run()

### ISSUE THREAD

**Issue by lequer** [mdeverdelhan/ta4j#39]
Currently, when running TimeSeries.run(strategy), the tradingRecord does not record the entry price for the trade ( with the use of operate(i) ), it always return Decimal.NAN. So the StopLossRule and the StopGainRule never actually work  when used like that. 
Now that you have TradingRecord.enter() and TradingRecord.exit(), is it possible to pass the trade amount and store the entry price when running the strategy?

Something along those line?
```java
    public TradingRecord run(Strategy strategy, OrderType orderType, Decimal amount) {

        log.trace("Running strategy: {} (starting with {})", strategy, orderType);
        TradingRecord tradingRecord = new TradingRecord(orderType);

        for (int i = beginIndex; i <= endIndex; i++) {
            // For each tick in the sub-series...
            if (strategy.shouldEnter(i, tradingRecord)) {
                tradingRecord.enter(i, amount, ticks.get(i).getClosePrice());
            }
            if (strategy.shouldExit(i, tradingRecord)) {
                tradingRecord.exit(i, amount, ticks.get(i).getClosePrice());
            }
        }
// ....
```
Thank you for the consideration.

**Comment by mdeverdelhan** [comment]
Whoops! Nice one!

I am more thinking about something like:
```java
public TradingRecord run(Strategy strategy, OrderType orderType, Decimal amount) {
    log.trace("Running strategy: {} (starting with {})", strategy, orderType);
    TradingRecord tradingRecord = new TradingRecord(orderType);
    for (int i = beginIndex; i <= endIndex; i++) {
        // For each tick in the sub-series...
        if (strategy.shouldOperate(i, tradingRecord)) {
            tradingRecord.operate(i, ticks.get(i).getClosePrice(), amount);
        }
    }
//...
```
... since some conditions are checked in the `Strategy#shouldOperate()` method. We just need to [re]add a `TradingRecord#operate(int, Decimal, Decimal)` method. Would you mind making a PR fixing this?

**Comment by lequer** [comment]
Sure thing, I'll do that today, hopefully I won't mess up, that would be my first pull request. I just learned how to synchronized your repos yesterday! It should be done by the time you get up in Marseille:)
