### ISSUE TITLE
Parabolic SAR

### ISSUE THREAD

**Issue by caffery-chen** [mdeverdelhan/ta4j#45]
Hallo, 

I am wondering whether there are some problems in the parabolic SAR indicator.

I compare the results with what I got in the MT4 platform. There apparently more flip point according to your calculation. Therefore, could you double chk your implementation?

Cheers,

**Comment by mdeverdelhan** [comment]
Hi,

Thank you for your interest. Unfortunatelly I don't have enough time for that.

It probably comes from the fact that some of the indicator implementations are controversial. Does the starting point of an EMA have to be the close price or a SMA? How to calculate the two first values (which are used to calculate the next ones) of the parabolic SAR? Etc. Often it's related to first values computation. It barely influences the results.

Anyway feel free to study the issue, explain in which way the current implementation is flawed, and make a pull request. :)

Marc

**Comment by caffery-chen** [comment]
ok, I will try to track it down.
