### ISSUE TITLE
StopLossRule does not work

### ISSUE THREAD

**Issue by emren** [mdeverdelhan/ta4j#48]
Hello, I am not able to make the StopLossRule work.
For example 
    
ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
RSIIndicator rsiIndicator = new RSIIndicator(closePrice, 40);
Rule entryRule = new CrossedUpIndicatorRule(rsiIndicator, Decimal.valueOf(60));
Rule exitRule = new StopLossRule(closePrice, Decimal.valueOf("1"));
    
does give me zero trades, it does not get out of trade even at real series where stop loss rules are satisfied. Also tried with 

Rule exitRule = new StopLossRule(closePrice, Decimal.ONE);

and getting zero trades. 
Thank you

**Comment by mdeverdelhan** [comment]
Thank you for your interest!

Please check if your entry rule is satisfied. You won't get any trade if your exit rule is satisfied but not your entry rule. See [this example](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/logging/StrategyExecutionLogging.java) to trace your strategy execution.

Marc

**Comment by emren** [comment]
Hi Marc, yes I did now and it seems my entry rule is satisfied

1185 [main] TRACE e.v.t.t.r.CrossedUpIndicatorRule - CrossedUpIndicatorRule#isSatisfied(5): true
1185 [main] TRACE eu.verdelhan.ta4j.Strategy - >>> Strategy#shouldEnter(5): true
1185 [main] TRACE e.v.ta4j.trading.rules.StopLossRule - StopLossRule#isSatisfied(6): false
1185 [main] TRACE eu.verdelhan.ta4j.Strategy - >>> Strategy#shouldExit(6): false

**Comment by mdeverdelhan** [comment]
OK. Could you post how do you build your strategy (i.e. your indicators, entry/exit rules)?

The StopLossRule is working for me. See also [its test class](http://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/test/java/eu/verdelhan/ta4j/trading/rules/StopLossRuleTest.java).
I don't have enough time to look deeper into your problem but I think that you should put a breakpoint (around or inside) the [`isSatisfied()`](http://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/trading/rules/StopLossRule.java#L54) method to check why it always returns false. Have a look to your `TradingRecord` object.

**Comment by cu39** [comment]
@emren Your problem may be related to #39
`TimeSeries#run` in ta4j-0.7 does not record the entry price into `TradingRecord`.
Try HEAD version (0.8-SNAPSHOT) if you have trouble with 0.7.

**Comment by emren** [comment]
Moving to 0.8-SNAPSHOT solved my problem. I was using 0.7 indeed.
Thank you @mdeverdelhan and @cu39

**Comment by mdeverdelhan** [comment]
I had already forgotten the #39. Thank you @cu39!

**Comment by cu39** [comment]
Once I got the same problem with Bollinger's then wrote my own `run` method
but I found #39 just after seeing this issue. Lucky for all :)
