### ISSUE TITLE
Sense of Decimal class?

### ISSUE THREAD

**Issue by ElMoe** [mdeverdelhan/ta4j#50]
I don't understand the purpose of the Decimal class: what is the benefit of using decimal numbers instead of timeseries data?

**Comment by mdeverdelhan** [comment]
The `Decimal` type is the way I found to represent the numbers in ta4j. Originally we were using the `double` primitive type, but it resulted in huge approximations in calculations over time. See also:
 * http://0.30000000000000004.com/
 * https://github.com/mdeverdelhan/ta4j/issues/4#issuecomment-47320887
 * https://github.com/mdeverdelhan/ta4j/issues/19#issuecomment-61825148
 * http://stackoverflow.com/questions/3413448/double-vs-bigdecimal
 * http://stackoverflow.com/questions/1359817/using-bigdecimal-to-work-with-currencies
 * And more, and more...

Now (i.e. it may change) `Decimal` delegates all the operations to `BigDecimal`, so it is based on BigDecimal's concepts (http://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html).
  
Feel free to update [the wiki](https://github.com/mdeverdelhan/ta4j/wiki) with explications about that if you think it's unclear.

**Comment by ElMoe** [comment]
Thank for the intorductory links to the Decimal topic!
You write that Decimal delegates to BigDecimal. I encounter some difficulties when i try BigDecimal synax on Decimal, e.g.:
For BigDecimal it's: BigDecimal b = new BigDecimal("2.0");
For Decimal it's: Decimal b = Decimal.valueOf("2.0");

Two questions:
What is there a reason that Decimal usages differ from BigDecimal?
Is it possible to simply cast a BigDecimal simply into Decimal?

I'll try to put an explication about the Decimal topic into the wiki.

**Comment by mdeverdelhan** [comment]
> 1.) What is there a reason that Decimal usages differ from BigDecimal?

I chose to simplify (at least according to me) the management of the numbers in ta4j. BigDecimal comes with a bunch of features I don't use (Math contexts, management of VERY big numbers, divide-by-zero exception, ...).

> 2.) Is it possible to simply cast a BigDecimal simply into Decimal?

It would be possible if Decimal was extending BigDecimal. If so, I would have inherit all the features I mentioned above, and I plan (some day) to refactor this class to avoid using BigDecimal.

**Comment by ElMoe** [comment]
Okay, thank you for the explications.
