### ISSUE TITLE
BB indicators’ multiplier K to be variable

### ISSUE THREAD

**Issue by cu39** [mdeverdelhan/ta4j#53]
I am planning to edit BB upper/lower indicators for their multiplier (usually called K) to be variable. Currently K is hard-coded as `Decimal.TWO`. [ref1](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/trackers/bollingerbands/BollingerBandsUpperIndicator.java#L50) [ref2](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/trackers/bollingerbands/BollingerBandsLowerIndicator.java#L50)

Two ways of implemantation:

 1. Creating a new abstract class for BB upper/lower and implement properties onto it.
 2. Implementing new prop on each of them independently.

Opt 1 is rather OOP and DRY approach but the name of new abstract is another question for me.
Opt 2 is viable for simple classes like them, though not DRY.

I would appreciate any suggestion from maitainer.

**Comment by mdeverdelhan** [comment]
Hi and thank you for your offer!

I would choose the 2nd option; even if it's not DRY it avoids looking for a relevant name as in the first option. Don't forget to update the test classes. ;)
