### ISSUE TITLE
ta4jexamples: question about BuyAndSellSignalsToChart.java

### ISSUE THREAD

**Issue by ElMoe** [mdeverdelhan/ta4j#54]
I have a questions about the mentioned example. In the class file is a method called 'buildChartTimeSeries':

private static org.jfree.data.time.TimeSeries buildChartTimeSeries(TimeSeries tickSeries, Indicator<Decimal> indicator, String name) {
        org.jfree.data.time.TimeSeries chartTimeSeries = new org.jfree.data.time.TimeSeries(name);
        for (int i = 0; i < tickSeries.getTickCount(); i++) {
            Tick tick = tickSeries.getTick(i);
            chartTimeSeries.add(new Minute(tick.getEndTime().toDate()), indicator.getValue(i).toDouble());
        }
        return chartTimeSeries;
    }

Question: Why is the 'indicator' argument needed for this method? 

You could change:
chartTimeSeries.add(new Minute(tick.getEndTime().toDate()), indicator.getValue(i).toDouble());
into:
chartTimeSeries.add(new Minute(tick.getEndTime().toDate()), tick.getClosePrice().toDouble();
because the method is called with 'ClosePriceIndicator(series)' for 'indicator'

(just to keep the method flexible?)

**Comment by mdeverdelhan** [comment]
Probably a copy/paste from another example.

The examples are not intended to be DRY, generic, or any-concept-you-want. However they have to be short, self contained (approximately), correct, compilable, easily maintainable, relevant (more or less).
