### ISSUE TITLE
HMA Indicator

### ISSUE THREAD

**Issue by dalamar66** [mdeverdelhan/ta4j#56]
To create a new Indicator for Hull Median Average:

The formula is:

WMA(2*WMA(PRICE, n/2) - WMA(PRICE, n), sqrt(n))

and WMA(PRICE, n) is defined as 

( PRICE * n + PRICE(1) * n-1 + ... PRICE(n-1) * 1) / ( n * (n + 1) / 2 )

**Comment by mdeverdelhan** [comment]
Hi!

Don't know this one. Would you provide any pointer about it? By the way: the WMA is already available in ta4j.

Marc

**Comment by dalamar66** [comment]
You can see the definition here:

https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/hull-moving-average

It is more suitable for strategies based on asset rotation (e.g Sectorial
ETFs).

WMA is required to implement this indicator, I'm already working on it.

**Comment by mdeverdelhan** [comment]
OK, Hull *moving* average, thank you for the definition.
Feel free to add it and make a PR. Don't forget to add a corresponding test class. But your main problem will certainly be: [how to compute the WMA when the timeframe (or period) is sqrt(n)?](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/trackers/WMAIndicator.java#L39) (Maybe using the integer part would be sufficient)

**Comment by mdeverdelhan** [comment]
Found a little bit of time/motivation and implemented it. I'll deploy that in 0.8-SNAPSHOT by the end of the week.

**Comment by dalamar66** [comment]
Thanks a lot!
