### ISSUE TITLE
Mocks for users?

### ISSUE THREAD

**Issue by cu39** [mdeverdelhan/ta4j#57]
Mock classes inside `eu.verdelhan.ta4j.mocks` package are useful for ta4j users to test their custom indicators and analysis criteria or to learn things in trial and error, while they're unavailable since `mocks` reside in `src/test/java`.

How about moving them to `src/main/java` ?

**Comment by mdeverdelhan** [comment]
I don't know yet if it's relevant. To be honest I'm currently thinking about turning Tick into an interface (and the user would choose the backend he wants).

**Comment by cu39** [comment]
To be frank, I’ve felt that making `List<Tick>` is a burden just for unit tests (which is the reason why `MockTimeSeries` is) or trials in disposable environment such as [javarepl](https://github.com/albertlatacz/java-repl).

Anyway it sounds good idea and I also hope that for `TimeSeries` as well as `Tick`. I guess it would be a major change that may break some compatibilities, though.
