### ISSUE TITLE
VWAP, MVWAP, TWAP, TMA and WMA

### ISSUE THREAD

**Issue by danarmstrong** [mdeverdelhan/ta4j#59]
Not sure if they are implemented and I'm just not seeing them, but I would be interest in seeing these indicators implemented.

**Comment by mdeverdelhan** [comment]
Hello and thank you for your interest!

For now only WMA is implemented (https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/indicators/trackers/WMAIndicator.java). But feel free to make a PR adding the others.

Marc
