### ISSUE TITLE
question: When buy/sell

### ISSUE THREAD

**Issue by GENiALi** [mdeverdelhan/ta4j#62]
Hi
I  have a little understanding problem.

I thought that strategy.shouldEnter(endIndex) is for buy. But, I think my thought is not correct. strategy.shouldEnter(endIndex) is for sell. Correct?

**Comment by mdeverdelhan** [comment]
Hi,

The "enter" may be what you decide (either buy or sell), but the "exit" is an order of the opposite type.
See also: https://github.com/mdeverdelhan/ta4j/blob/ta4j-0.7/ta4j/src/main/java/eu/verdelhan/ta4j/Trade.java#L27 (and update if you think it should be clearer)

Marc

**Comment by GENiALi** [comment]
Hi
OK. Now I see it. It's depends from my strategy. e.g. https://github.com/mdeverdelhan/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/strategies/RSI2Strategy.java
`Rule entryRule` is a buy signal. When i change the definition with the exitRule definition, then is it a sell signal. My rule says what for a signal it is.

**Comment by diego1982chile** [comment]
i'm sorry, but i have similar question..because when
series.run(strategy) is called, it calls its overloaded method
with OrderType.BUY by default, so it always performs a BUY
unless of course we explicitly specify the order type. But
then the strategy should know when to apply a BUY or a SELL,
is there an example of this?

**Comment by mdeverdelhan** [comment]
Hi! Please don't be sorry. :)

The strategy has to know an entry rule and an exit rule. Then it's up-to-you to decide what is your entry order type (and thus your exit one). Such a feature has been added to manage the case of when you start running a strategy with assets in your wallet (for instance, when you already owns some stocks/commodities/etc. when starting the execution).

And no, I don't have any simple example of this.

**Comment by diego1982chile** [comment]
Hi,

Thanks for quick reply..

I'm not sure if i'm getting it well, but i tried implementing macd strategy on ta4j.
A typical macd strategy consists of an macd indicator plus an ema for signal:
When macd crosses up the ema then buy
Wehn macd crosses down the ema then sell
so the way i find to implement this on ta4j would be by
building two strategies, one for buy signal and second for sell signal
for example:

+         MACDIndicator macd= new MACDIndicator(closePrice,12,26);

 +        EMAIndicator ema= new EMAIndicator(closePrice,9);
 +        
 +        Rule entryRule1 = new CrossedUpIndicatorRule(ema,macd);                
 +        Rule exitRule1 = new CrossedDownIndicatorRule(ema,macd);
 +        
 +        Strategy strategy1 = new Strategy(entryRule1, exitRule1);                       
 +        
 +        TradingRecord tradingRecord1 = series.run(strategy1, Order.OrderType.BUY);
 +        
 +        Rule entryRule2 = new CrossedDownIndicatorRule(ema,macd);                
 +        Rule exitRule2 = new CrossedUpIndicatorRule(ema,macd);
 +        
 +        Strategy strategy2 = new Strategy(entryRule2, exitRule2);                       
 +        
 +        TradingRecord tradingRecord2 = series.run(strategy2, Order.OrderType.SELL);     

am i right?

Thanks, and regards

**Comment by dan-lind** [comment]
Perhaps it would be clearer if it was OrderType Long and Short, rather than Buy and Sell? Or did I missunderstand as well? ?

**Comment by mdeverdelhan** [comment]
@diego1982chile
You are wrong! Your "strategy1" is sufficient.
If entryRule1 is your buying rule, exitRule1 is the selling one. If you buy to enter, you will have to sell to exit. Entries and exits have opposite order types. Don't know how to say it some other way.

@dan-lind 
You are understanding well. But I don't want to work for guys who don't know that Long means Buy and Short means Sell. Ta4j is not for wanabee traders or full newcomers.

@Everyone
Feel free to update the wiki if you think that should be clearer: https://github.com/mdeverdelhan/ta4j/wiki/Trading%20strategies

**Comment by diego1982chile** [comment]
Hi,

Thanks for replies, 

mdeverdelhan, i did notice what you said, but in more a realistic scenario,
macd needs some additional conditions, like distance between 0 line and
crossing point, anyway i will give more attention on your explanation 
probably i'm still missing something...

thanks for your time on this

PS: I did knew that long meand buy, and short means sell ;)

**Comment by mdeverdelhan** [comment]
Don't hesitate to update the lib and make a PR if you think it's worthwhile.

For me you can build any strategy with the current trading rule engine (except that all your rules have to work on the same time series, I know: I have to think about it).
Trading rules use the "builder" design pattern. Thus you can combine them using boolean logic (and add the conditions you want). For instance: Rule entryRule = macdCrossUpRule.or(otherRule.and(otherOtherRule));
See: https://github.com/mdeverdelhan/ta4j/wiki/Trading%20strategies#trading-rules

PS: I was speaking generally, you were not targeted. :)
