### ISSUE TITLE
Typical enter rule parameters to test for intra day 

### ISSUE THREAD

**Issue by jainhj** [mdeverdelhan/ta4j#65]
Hi, I recently saw ta4j. First of all thanks for contributing and sharing. I wanted to test out some of the indicators in India NSE market for intra day. Was trying with the moving momentum example which has been shared. However my enter rule was not getting satisfied. I might be missing something. I was taking a 10 second interval. In that interval I am finding open, close, high, low and traded volume. With that 10 second data I am creating a tick and adding to a time series. I initialized time series with maximum 100 ticks. Wanted to check if I am configuring it right.

**Comment by dan-lind** [comment]
Would be nice to see some code :-)

**Comment by jainhj** [comment]
[MomentumStrategy.txt](https
[ochl.txt](https://github.com/mdeverdelhan/ta4j/files/95987/ochl.txt)
://github.com/mdeverdelhan/ta4j/files/95986/MomentumStrategy.txt)
Please see analyze method of MomentumStrategy.txt

**Comment by jainhj** [comment]
Looks like file was not uploaded. Putting the code here - 

protected void init(MultiInstrumentStrategy strategy) {
		if (!initialized) {
			int seriesInterval = 10;
			series = new TimeSeries("momentum_series", Period.minutes(seriesInterval));
			series.setMaximumTickCount(seriesInterval*10);
			for(Instrument instr: strategy.getData().getInstrumentData().values()) {
				leg = instr;
			}
			momentumStrategy = buildStrategy(series);
			initialized = true;
		}
	}
	
	protected double getVolumeFromLastTick(Quote quote) {
		Decimal lastVolume = Decimal.valueOf(0);
		int tickCount = series.getTickCount();
		if (tickCount > 0 ) {
			Tick lastTick = series.getLastTick();
			lastVolume = lastTick.getAmount();
		}
		double volume = quote.getTotalVolume() - lastVolume.toDouble();
		return volume;
	}

public PriceInstruction analyze(MultiInstrumentStrategy strategy) {
		
		init(strategy);
		
		Quote quote = strategy.getQuote(leg.getSymbol());
		if (!QuoteUtil.isQuoteValid(quote)) {
			log.info("Recieved Invalid Quote. Quote:" + quote);
			return null;
		}
		currentOchl.processQuote(quote);
		
		if(null == binTime || TimeUtil.getTimePass(binTime) > 10000) {
			binTime = Clock.getInstance().now();
		} else {
			return null;
		}
		
		double volume = getVolumeFromLastTick(quote);
		double close = currentOchl.close;
		
		series.addTick(new Tick(DateTime.now(), currentOchl.open, currentOchl.high, currentOchl.low, close, volume));
		currentOchl.reset(close);
		
		int endIndex = series.getEnd();
        if (momentumStrategy.shouldEnter(endIndex)) {
        	
        	boolean entered = tradingRecord.enter(endIndex, Decimal.valueOf(close), Decimal.TEN);
        	
             // Our strategy should enter
             log.info("Strategy should ENTER on " + endIndex);
             
         } else if (momentumStrategy.shouldExit(endIndex)) {
        	 
         }

		return null;
	}

**Comment by mdeverdelhan** [comment]
Hi!
Which version of ta4j are you using? There is a huge issue in the `0.7` (see #39). I strongly advise you to use the `0.8-SNAPSHOT`.

**Comment by jainhj** [comment]
ok, thanks. I was using 0.7. Would switch to 0.8-snapshot
