### ISSUE TITLE
How to get a TradingRecord when using chooseBest() ?

### ISSUE THREAD

**Issue by dan-lind** [mdeverdelhan/ta4j#66]
It's been a while since I used ta4j, and I've spent some time getting my application up to date with 0.8-SNAPSHOT.
One thing we had before is Decision, which could be used when evaluating multiple strategies, something along these lines:
```       
List<Strategy> strats = new ArrayList<Strategy>();

strats.add(...);

TotalProfitCriterion criterion = new TotalProfitCriterion();
Decision dec = criterion.chooseBest(series, strats);
dec.evaluateCriterion()
```
You would then know the criterion value for the chosen strategy.

My understanding is that Decision has now been replaced (kinda) by TradingRecord.
I was wondering if it's possible to get a TradingRecord when using chooseBest(), without rerunning the  strategy returned by chooseBest() ? 

I'm currently doing something along these lines, which means that the chosen strategy is executed twice; once when evaluating it against the other strategies, and then again to get a TradingRecord:
```
TotalProfitCriterion criterion = new TotalProfitCriterion();
Strategy strategy = criterion.chooseBest(series, strats);

TradingRecord tradingRecord = series.run(strategy);
criterion.calculate(series, tradingRecord);
```

Is there any way of avoiding executing the strategy twice in order to get a TradingRecord?

**Comment by mdeverdelhan** [comment]
Why not? But I don't know how to do this without re-adding an irrelevant type like `Decision`. Something like a `Pair<F, S>` would be usefull here. :/

By the way, the `AnalysisCriterion#chooseBest(TimeSeries, Strategy...)` is mainly a convenient method to get an approximately "best" Strategy. In fact it may also depend on your entry order type and on the amount of your order (the "chooseBest()" method doesn't take them into account as it calls [`run(...)`](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeries.java#L387) and not [`run(...)`](https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeries.java#L411)).

Thus, no! For now you have to run your strategy twice or to reimplement the `chooseBest(...)` method.

**Comment by dan-lind** [comment]
Thanks, great to know!
