### ISSUE TITLE
Create FISHER indicator

### ISSUE THREAD

**Issue by junajo10** [mdeverdelhan/ta4j#70]

**Comment by mdeverdelhan** [comment]
Hi,

Feel free to add a description or any pointer that could help. If your indicator is relevant don't hesitate to make a pull request. I'll be glad to merge it.

Marc

**Comment by junajo10** [comment]
Fisher = https://c.mql4.com/forum/2010/04/fisher.mq4

Also i have a question:
Last = Last Price
OpenLong  = A>B                 AND Last crosses below A
OpenShort = C<D       AND Last crosses above B

CloseLong  = Last crosses above A
CloseShort = Last crosses below C

is it posible to distinguish between LONG and SHORT?

Rgds,

JJ

**Comment by mdeverdelhan** [comment]
Actually I was more thinking about a full explanation (with formula explained especially). Algorithms are often controversial. Then someone may find it interesting enough to implement it.

Please don't mix different topics in the same issue. LONG and SHORT can be distinguished. They are called BUY and SELL respectively. See the OrderType and its usages: https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/Order.java

**Comment by mdeverdelhan** [comment]
Someone worked on the Fisher during the last week. You may see something in a few days.

**Comment by gcauchis** [comment]
FISHER indicator is added in pull request #76 .

**Comment by mdeverdelhan** [comment]
@gcauchis Thank you for @junajo10 !
