### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by jainhj** [mdeverdelhan/ta4j#71]
There is a bug in last stable release 0.7 because of which it was advised to use snapshot. Can a new version be released.

**Comment by mdeverdelhan** [comment]
I plan to release a 0.8 when we will reach more than 100 technical indicators. I think we are approx at 85-90 now (from 50-55 in the 0.7). Feel free to add some if you want to accelerate the process. :)

**Comment by jainhj** [comment]
Thanks for the response. Please let me know about an indicator which you want to add. I should be able to get time in Feb end.

**Comment by mdeverdelhan** [comment]
Any indicator that may be useful in the technical analysis domain. Basically an indicator is just 2 classes: the indicator itself and its test class. If should be the case you will be added to the list of authors.

Some [not yet implemented] examples:
  * http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:chandelier_exit
  * http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:vortex_indicator
  * http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:know_sure_thing_kst
  * http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:dppmo
  * http://www.investopedia.com/terms/c/chandemomentumoscillator.asp & http://tradingsim.com/blog/chande-momentum-oscillator-cmo-technical-indicator/
  * http://www.investopedia.com/terms/k/klingeroscillator.asp & http://www.positiveterritory.com/do/tw/kvo11.htm
  * http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:force_index
  * http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:volatility_index
  * http://www.investopedia.com/terms/g/guppy-multiple-moving-average.asp
  * Kalman Filter
  * Pivot Points
  * Fibonacci Retracements
  * Vertical Horizontal Filter
  * Variable Index Dynamique Average
  * Range Action Verification Index
  * and more, and more...

**Comment by mdeverdelhan** [comment]
Ta4j 0.8 has been released.
