### ISSUE TITLE
Question on backtesting strategies with indicators calculated with enough ticks

### ISSUE THREAD

**Issue by junajo10** [mdeverdelhan/ta4j#74]
I would like to know if it is posible not to run until all my indicators have been calculated.
For example, 
Ema(25)
Ema(50)
I need at least max(25,50) ticks, then i would like to run when 50 ticks have been loaded, so my indicators will be used correctly and i don't generate wrong signals.

Pseudo code could be:

Series.run(strategy, minimumticks)->code discard minimumticks and then begin to backtest,so i will be sure i have enought ticks to operate correctly.

**Comment by mdeverdelhan** [comment]
You mean something that TA-lib is providing: http://ta-lib.org/d_api/ta_setunstableperiod.html Isn't it?

Sounds like a relevant idea. Maybe giving the start index or the minimum ticks count as an argument of the run() method would be sufficient. I will consider the question soon.

**Comment by junajo10** [comment]
Yes, it is that topic http://ta-lib.org/d_api/ta_setunstableperiod.html. 
I will wait this feature.

Thanks a lot

**Comment by mdeverdelhan** [comment]
For now the unstable period can be set for a strategy by calling the corresponding setter on this strategy.
See also: https://github.com/mdeverdelhan/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/Strategy.java#L77
