### ISSUE TITLE
Adding a "pairs trading" example

### ISSUE THREAD

**Issue by junajo10** [mdeverdelhan/ta4j#75]
I think your library is very powerful 
Ta4j could be more complete if you'd add a "pairs trading" example,
TimeSeries series1 = CsvTradesLoader.loadA();
TimeSeries series2 = CsvTradesLoader.loadB();
// Building the trading strategy
Strategy strategyA = buildStrategyA(series1); 
Strategy strategyB = buildStrategyB(series2); 

 TradingRecord tradingRecord = series.run(strategyA,Buy);
 TradingRecord tradingRecord = series.run(strategyB,Sell);
............................

public static Strategy buildStrategyA(TimeSeries series) {
A, B, having price series A(t), B(t)
ratio time series R(t) = A(t) / B(t)
apply moving average of type T with period Pm on R(t) to get time series M(t)
apply standard deviation with period Ps on R(t) to get time series S(t)
create Z-score series Z(t) as Z(t) = (R(t) - M(t)) / S(t)
Set entry threshold En for Z-score, typical value range is <1.5, 2.5>
       exit threshold Ex for Z-score, typical value is <-0.5, 0.5>
...................
} 
StrategyB will be the same, rule entry and rule exit will be opposite.

**Comment by mdeverdelhan** [comment]
The examples are mainly [SSCCEs](http://sscce.org/) used to show how ta4j can interact with other libs or just how to handle a general usage. A new one need to be maintained over time like the others, and yours seems to be very specific. Moreover I know that working on several time series at same time with ta4j leads to strange behaviors.
Anyway if you don't mind making a pull request, I will look at it.

**Comment by RuralHunter** [comment]
I have a similar question. My stock trade strategy is based on both the stock ticks and the market index ticks. The index/position of the both ticks are not one-one pair because the stock ticks maybe missing on some days because of trade stop while the market opens. The only relation I can get for both ticks is the date. 
I looked around in current code and samples and it seems there is no easy way to implement this. Any idea/suggestion on the best way to implement this?

**Comment by RuralHunter** [comment]
OK, I implemented this by create another rule which uses the rule from the stock and the indicator from the market index.  Pls kindly let me know if there is other better solution.

@Override
    public boolean isSatisfied(int index, TradingRecord tradingRecord)
    {
        int tickIndex=getTickIndexByEndTime(series.getTick(index).getEndTime());
        return rule.isSatisfied(index)&&marketIndicator.getValue(tickIndex).isPositive();
    }


    /**
     * Find the tick index by time
     *
     * @param time the end time of the required tick
     * @return The index of the tick which has the same endTime
     */
    protected int getTickIndexByEndTime(DateTime time)
    {
        TimeSeries marketSeries=marketIndicator.getTimeSeries();
        for(int i=0; i<marketSeries.getTickCount(); i++)
        {
            Tick t=marketSeries.getTick(i);            
            if(time.equals(t.getEndTime()))
                return i;
        }
        return -1;
    }

**Comment by mdeverdelhan** [comment]
You identified some weaknesses of ta4j: multi-series, time synchronization, etc.
And no, for now there is no simple way to do what you want.

Those problems question the whole lib design. They are also very dependent of the identified use cases. Starting to implement such stuff without a deep thinking would be like skating on thin ice. Your rule seems to be an acceptable workaround but it's "in your case". For instance: in real life you have to handle the -1 case, what if your dates are not in the same base, etc. Time management in industrial apps is a problem I know very well (mainly in aeronautics, but I found it in various other domains, like trading) and, for now, I don't have enough time to address it in ta4j.

**Comment by RuralHunter** [comment]
OK, thanks for the response. I understood. for now, my solution is enough for my case.
