### ISSUE TITLE
Question about eu.verdelhan.ta4j.mocks and Maven

### ISSUE THREAD

**Issue by ElMoe** [mdeverdelhan/ta4j#79]
Hi there,
i have the following problem in my Netbeans project:
For a JUnit test i'd like to use eu.verdelhan.ta4j.mocks. But unfortunately eu.verdelhan.ta4j.mocks is not included in the official Maven repository "eu.verdelhan.ta4j" release 0.8 with scope "Testing". 
Is it possible to add "mocks" to the repository for the testing scope?
Any other ideas?
Regards,
Elmoe

**Comment by mdeverdelhan** [comment]
Ta4j is not intended to be a test dependency. Which one of the mock objects would you like to use? I may add it in the regular lib as basic objects.

**Comment by ElMoe** [comment]
I'd need "eu.verdelhan.ta4j.mocks.MockTimeSeries".

I just need "mocks" for the discussed conversion class [https://github.com/mdeverdelhan/ta4j/issues/61](url).

When i pull "ta4j" from github, everything is fine and i find "mocks" in the testing package. But going this way i'd need to include the github sources for MockTimeSeries in the Maven project manually in the POM, which is also not very handsome.

Is it possible to configure Maven so that "mocks" is only included for scope "testing"?

**Comment by gcauchis** [comment]
Hi!

if you have checkout ta4j, run the maven commande `mvn jar:test-jar install`.

Then add to your pom the following dependency:
```xml
<dependency>
    <groupId>eu.verdelhan</groupId>
    <artifactId>ta4j</artifactId>
    <version>0.8-SNAPSHOT</version>
    <type>test-jar</type>
    <scope>test</scope>
</dependency>
```
Now you have access to the mock package in your project in local.

**Comment by ElMoe** [comment]
Thank you very much!
