### ISSUE TITLE
TimeSeries always iterates over all the data

### ISSUE THREAD

**Issue by BrynCooke** [mdeverdelhan/ta4j#80]
Hi I've been experimenting with ta4j and would like to create a TimeSeries using a memory map backed list. The only issue is that the creating a TimeSeries always iterates over the entire dataset to calculate the timePeriod. 
I already know the timePeriod so would it be possible to add the ability to specify this manually?

**Comment by mdeverdelhan** [comment]
Hi,

What if the period of the time series does not match the period of the tick?
I understand the problem but I think it would need a deeper thinking before roughly accepting your PR.

Marc

**Comment by BrynCooke** [comment]
Could this be something that is calculated on demand rather than in the constructor? It could even cache the value for subsequent calls.

**Comment by mdeverdelhan** [comment]
Of course! I will try to address the problem as the same time as #81.

**Comment by mdeverdelhan** [comment]
Finally I just removed the time period. I realized that I don't know any relevant use case of it since it's an approximation.
