### ISSUE TITLE
Tick uses Period of 24H when it possibly means 1 Day

### ISSUE THREAD

**Issue by doo-gl** [mdeverdelhan/ta4j#81]
Hi Marc,

I'm liking the library, it's good. 

I had been doing a bit of work with Ticks over a range of times and I've found something that I think is a bug.

When a Tick is initialised without specifying a period, the period is set to

`Period.days(1)`

Which represents a time period of 24H as opposed to a time period of 1D. Of course for the majority of the time there is no difference, except when a barrier between daylight savings is reached. Adding 24H to the day is different to adding 1D and so you find that your expected times are off by one hour.

This can be side-stepped by specifying the Period when the Tick is created to be 

`Days.days(1).toPeriod()`

But then there is an issue when using TimeSeries with the constructor that only uses a List of Tick It calculates the Period for the TimeSeries as 24H and ignores the Period values held in the Ticks. 

This can also be side-stepped by Initializing TimeSeries with the Period 1D and then manually adding all the Ticks to the TimeSeries.

So, while both of these issues can be side-stepped, it would be good to fix these cases, because it can cause confusion. Particularly, when a developer thinks a period is one day (and rely on Joda to take care of the complicated time-based math) and when it is actually 24 hours (and so Joda does not take care of the complicated time-based math).

Thanks,

Doogal

**Comment by mdeverdelhan** [comment]
Hi,

Daylight savings, nice shot. :/
I will try to find some time to start time management afresh in series.

Marc

**Comment by mdeverdelhan** [comment]
Same as #80:
I removed the time period field from the time series. I also turned the `Period.days(1)` in the Tick into `Days.days(1).toPeriod()`.
