### ISSUE TITLE
AverageTrueRangeIndicator - Returns Decimal.ONE at Index(0)

### ISSUE THREAD

**Issue by hany10** [mdeverdelhan/ta4j#88]
Hi,
I'm trying to use Keltner channel Indicator with Forex time series. I noticed that the upper and lower Keltner boundaries start with large gap from the middle Keltner line. I also found that the lower Keltner boundary starts with negative value. I traced the issue back to the AverageTrueRangeIndicator where I discovered the condition that returns Decimal.ONE at Index(0).

Normally Forex prices are very low ranging around 0.xxxx and 1.xxxx  and starting with ONE in the Channel calculations would cause the lower Keltner boundary to start with negative value in addition to the initial large gap between the two boundaries. Eventually, the two Keltner channel boundaries will converge to the true value, but it will take longer.  
As a temporary workaround, I've modified the AverageTrueRangeIndicator to return "**return tr.getValue(index);**" at index(0) in order to speed up the conversion to the correct long term average. My question is, will that cause problems down the track?

### ```
protected Decimal calculate(int index) {
   if (index == 0) {
   // return Decimal.ONE;
    return tr.getValue(index);
     }

**Comment by mdeverdelhan** [comment]
Hi,

ATR is, like many other indicators, calculated over a certain number of periods. For all of these indicators, as long as you did not reach the timeframe-th index you are in an "unstable" state. During this phase, all the results you may get before is not completely wrong, but it is neither completely right. Therefore you cannot expect to have correct-and-validated-be-everyone results in this degraded mode (you even switch to what I would call a "very degraded mode" by calling atr.getValue(0)). The most important point is that the process has to converge over time.

Anyway, your proposal seems relevant as it takes into account the scale of the underlying values. Feel free to fix this and make a PR. Don't forget to update the unit tests.

Thank you!

Marc
