### ISSUE TITLE
What about creating a link section in the wiki for related projects?

### ISSUE THREAD

**Issue by ElMoe** [mdeverdelhan/ta4j#92]
Hi,
i think there are a lot of good extensions out there for ta4j. What about creating a link section in the wiki for related projects and libraries? 

May be this can help boosting the use the library.

Best regards,
ElMoe

**Comment by mdeverdelhan** [comment]
Why not! I don't know those extensions, but feel free to add this section!

**Comment by ElMoe** [comment]
Hi, i added a menu item [related projects](https://github.com/mdeverdelhan/ta4j/wiki/Related-projects) with three sections containing related libraries and applications.

I added also one section for code that comes in as a pull request but wasn't integrated in ta4j ("quandl_loader").

**Comment by mdeverdelhan** [comment]
Nice job! I am going to have a look to those projects.
Thank you! :)
