### ISSUE TITLE
CashFlow not accounting for final trade if it is still open at end of time series

### ISSUE THREAD

**Issue by dan-lind** [mdeverdelhan/ta4j#94]
Not sure if this is a bug or by design, however I would consider it unorthodox compared to other trading software. 

CashFlow only considers trades that has been opened AND closed, it does not consider positions that are still open at the end of a time series. 

The following picture explains what I mean. Here I have plotted a chart where I'm using a simple SMA long/short cross strategy. Buy if short crosses long from below, sell if short crosses long from above.

The black line shows where the last position is opened (I confirmed by looking at the TRACE output)
In this scenario I would like the cashflow to indicate my position value, even though it was not closed before the time series ended. 

I hope it is clear what I mean.

<img width="881" alt="screenshot 2016-06-09 09 06 03" src="https://cloud.githubusercontent.com/assets/433464/15921570/9bff3c7c-2e22-11e6-8bfb-8729eeb1645a.png">

**Comment by dan-lind** [comment]
Closing the last order by doing something along these lines seems to do the trick for now.

```
Strategy mediumOverPrimary = MovingAverages.buildSimpleMovingAverageStrategy(series, 50, 200);

TradingRecord tradingRecord = series.run(mediumOverPrimary);

if (tradingRecord.getCurrentTrade().isOpened()) {
     tradingRecord.operate(series.getTickCount()-1);
}
```

**Comment by mdeverdelhan** [comment]
It is clear and it is a design choice.
People who made this considered that to calculate the cash flow you have to be in the same "state" (i.e. all trades closed) at the end of the series than at the beginning.

**Comment by dan-lind** [comment]
> "...you have to be in the same "state" (i.e. all trades closed) at the end of the series than at the beginning."

Not sure is a typo in there somewhere, but I didn't understand this explanation. 
You mentioned same state i..e all trades closed. You mean that I'm responsible for closing all trades? (Like I did in my second post)

**Comment by mdeverdelhan** [comment]
Sorry I wrote too fast.
The question is: is the cash flow concept relevant if it is calculated when you still have commodities/assets/stocks in hands? You don't have to close all your trades, but the last one won't be taken into account if it isn't closed. In fact, it is not really "existing" yet. You just placed an entry order, then the cash flow you estimate is at best theoretical until the exit order is executed.

By the way I don't use this cash flow calculator. So feel free to update it (and its tests) if you like. For a long time I want to refactor it and make it a real indicator but (as usual) it comes with numerous questions and I lack of time.

**Comment by dan-lind** [comment]
Are you using something else in its place? I only use it for plotting.

**Comment by mdeverdelhan** [comment]
I don't. For the analysis I just need to plot the time series and indicators (for now).
