### ISSUE TITLE
Not possible to change amount by EntryRule

### ISSUE THREAD

**Issue by DennisPiskovatskov** [mdeverdelhan/ta4j#95]
after

`final TradingRecord tradingRecord = series.run(bestStrategy);`

not possible to change amount. Just for example the amount can be calculated by Indicator and can be different from trade to trade.

**Comment by dan-lind** [comment]
Check https://github.com/mdeverdelhan/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/bots/TradingBotOnMovingTimeSeries.java, I think that gives an example where you could change amount between trades.

**Comment by mdeverdelhan** [comment]
Thank you @dan-lind
