### ISSUE TITLE
Not possible to add meta data to Trade

### ISSUE THREAD

**Issue by DennisPiskovatskov** [mdeverdelhan/ta4j#96]
it would be very helpful to add additional meta data to the trade by entry or exit rule. This can give the overview of the *Rule statistics and can be very helpful for the analysis. For example, if you are using OrRule(), which part of the condition was executed (is equals true) to start the trade and so on. It is very complicated to find necessary information in the produced log.

**Comment by mdeverdelhan** [comment]
It seems relevant. But we have to think twice about it: meta data should be associated to Trade? Order? I don't want the Order (or Trade) knowing the Rule/Strategy part. Etc.
Feel free to explain your design in details and we will look deeper into it. Then you can make a PR.
